// 확정 제안(제품 초안) 카드 4개 언어 카피 — DM(로컬)·BD(실서버) 포털이 공유
// 확정 제안 → 디파짓 flow 카피 (Request → Proposal → Deposit → Production)
export const PROPOSAL_FLOW_COPY = {
  en: {
    journeyRequest: "Request", journeyRequestSub: "Submitted",
    journeyProposal: "Proposal", journeyProposalSubNow: "Confirm now", journeyProposalSubPrep: "Preparing",
    journeyDeposit: "Deposit", journeyDepositSub: "Zelle / Venmo",
    journeyProduction: "Production", journeyProductionSub: "CAD → Final → Ship",
    proposalKicker: "Your proposal",
    preparingTitle: "We are preparing your proposal.",
    preparingBody: "BeloveD is matching a stone to your specifications and confirming the total price with our ateliers. You will review one proposal here — usually within 24–48 hours.",
    specStone: "Stone", specGrade: "Grade", specCert: "Certificate", specSetting: "Setting", specLead: "Lead time",
    specMetal: "Metal", weightApprox: (g) => `≈ ${g} g`, designNote: "Design adjustment",
    pieceTitle: "Your piece", priceTitle: "Your price",
    totalLabel: "Total, all-inclusive",
    totalMeta: "Setting, stone, labor, shipping and insurance included — no hidden fees.",
    depositToday: "Deposit — today", balanceShip: "Balance — before shipping",
    subTitle: "Equivalent substitution",
    subBody: "Depending on availability, this stone may be replaced with another certified stone of equal or better specs (±0.03 ct, same color/clarity grade or higher). If that happens, we send the new IGI number and video first and proceed only after your OK.",
    confirmCta: "Confirm this proposal", confirmedBadge: "Confirmed",
    payTitle: "Reserve with deposit", payAfter: "After you confirm",
    memoLabel: "Payment memo", memoRequired: "Required",
    payStep1: "Scan a QR — or copy the recipient and send from your app.",
    payStep2: "Paste this memo with your payment. We can only confirm transfers that include your order number.",
    payStep3: "Sent it? Let us know below.",
    copyRecipient: "Copy recipient",
    zelleHint: "No fee · fast confirmation", venmoHint: "Same-day confirmation",
    copyBtn: "Copy", copiedBtn: "Copied ✓",
    depositSentCta: "I've sent the deposit", balanceSentCta: "I've sent the balance",
    sentHelp: "We confirm within 1 business day, lock your stone, and email you right away.",
    reportedBadge: "Confirming transfer",
    reportedNote: "Payment reported. BeloveD is confirming the transfer — we'll email you as soon as your stone is locked.",
    doneBadge: "Deposit confirmed",
    balanceTitle: "Balance payment",
    balanceReportedNote: "Thanks — we'll confirm the balance shortly and prepare shipping.",
    nextConfirm: "Review and confirm your proposal.",
    confirmingDeposit: "Deposit reported — BeloveD is confirming the transfer.",
    nextBalance: "Send the balance to finish shipping preparation.",
  },
  ko: {
    journeyRequest: "요청", journeyRequestSub: "제출 완료",
    journeyProposal: "제안", journeyProposalSubNow: "지금 컨펌", journeyProposalSubPrep: "준비 중",
    journeyDeposit: "디파짓", journeyDepositSub: "Zelle / Venmo",
    journeyProduction: "제작", journeyProductionSub: "CAD → 완성 → 배송",
    proposalKicker: "제안",
    preparingTitle: "제안을 준비하고 있습니다.",
    preparingBody: "BeloveD가 아뜰리에와 함께 고객님 스펙에 맞는 스톤과 총액을 확정하는 중입니다. 보통 24–48시간 안에 이 화면에서 제안 1건을 확인하실 수 있어요.",
    specStone: "스톤", specGrade: "등급", specCert: "감정서", specSetting: "세팅", specLead: "제작 기간",
    specMetal: "메탈", weightApprox: (g) => `≈ ${g} g`, designNote: "디자인 조정",
    pieceTitle: "당신의 피스", priceTitle: "가격",
    totalLabel: "총액 (올인클루시브)",
    totalMeta: "세팅 · 스톤 · 세공 · 배송 · 보험 포함 — 숨은 비용 없음.",
    depositToday: "디파짓 — 지금", balanceShip: "잔금 — 배송 전",
    subTitle: "동급 대체 안내",
    subBody: "확보 시점에 따라 이 스톤은 동일 또는 상위 스펙(캐럿 ±0.03, 같은 컬러·클래리티 등급 이상)의 다른 인증 스톤으로 대체될 수 있습니다. 대체 시 새 IGI 번호와 실물 영상을 먼저 보내드리고, 동의 후에만 진행합니다.",
    confirmCta: "이 제안으로 확정", confirmedBadge: "컨펌 완료",
    payTitle: "디파짓으로 예약 확정", payAfter: "컨펌 후 진행",
    memoLabel: "송금 메모", memoRequired: "필수",
    payStep1: "QR을 스캔하거나, 받는 계정을 복사해 앱에서 보내세요.",
    payStep2: "송금 메시지에 이 메모를 붙여넣어 주세요. 주문번호가 있어야 입금을 확인할 수 있습니다.",
    payStep3: "보내셨으면 아래 버튼으로 알려주세요.",
    copyRecipient: "받는 계정 복사",
    zelleHint: "수수료 없음 · 빠른 확인", venmoHint: "당일 확인",
    copyBtn: "복사", copiedBtn: "복사됨 ✓",
    depositSentCta: "디파짓 보냈어요", balanceSentCta: "잔금 보냈어요",
    sentHelp: "영업일 기준 24시간 내에 입금을 확인하고 스톤을 락한 뒤 바로 이메일로 알려드립니다.",
    reportedBadge: "입금 확인 중",
    reportedNote: "송금 보고가 접수됐습니다. BeloveD가 입금을 확인하는 중이며, 스톤이 락되는 즉시 이메일로 알려드려요.",
    doneBadge: "디파짓 확인 완료",
    balanceTitle: "잔금 결제",
    balanceReportedNote: "감사합니다 — 곧 잔금을 확인하고 배송을 준비할게요.",
    nextConfirm: "제안을 확인하고 컨펌해 주세요.",
    confirmingDeposit: "송금 보고 완료 — BeloveD가 입금을 확인하는 중입니다.",
    nextBalance: "잔금을 보내주시면 배송 준비가 마무리됩니다.",
  },
  zh: {
    journeyRequest: "需求", journeyRequestSub: "已提交",
    journeyProposal: "方案", journeyProposalSubNow: "立即确认", journeyProposalSubPrep: "准备中",
    journeyDeposit: "定金", journeyDepositSub: "Zelle / Venmo",
    journeyProduction: "制作", journeyProductionSub: "CAD → 成品 → 发货",
    proposalKicker: "您的方案",
    preparingTitle: "正在准备您的方案。",
    preparingBody: "BeloveD 正在与工坊确认符合您规格的钻石与总价。通常 24–48 小时内，您将在此确认一份方案。",
    specStone: "钻石", specGrade: "等级", specCert: "证书", specSetting: "镶嵌", specLead: "制作周期",
    specMetal: "金属", weightApprox: (g) => `≈ ${g} g`, designNote: "设计调整",
    pieceTitle: "您的作品", priceTitle: "价格",
    totalLabel: "总价（全包）",
    totalMeta: "含镶嵌、钻石、工费、运费与保险 — 无隐藏费用。",
    depositToday: "定金 — 现在", balanceShip: "尾款 — 发货前",
    subTitle: "同级替换说明",
    subBody: "视库存情况，此钻石可能替换为规格相同或更优（±0.03 克拉，同级或更高颜色/净度）的其他认证钻石。如有替换，我们会先发送新的 IGI 编号与实物视频，征得您同意后才继续。",
    confirmCta: "确认此方案", confirmedBadge: "已确认",
    payTitle: "支付定金锁定", payAfter: "确认后开放",
    memoLabel: "转账备注", memoRequired: "必填",
    payStep1: "扫描二维码，或复制收款账号后在应用中转账。",
    payStep2: "付款时请粘贴此备注。备注中必须包含订单号，我们才能确认到账。",
    payStep3: "已转账？请点击下方按钮告知我们。",
    copyRecipient: "复制收款账号",
    zelleHint: "免手续费 · 快速确认", venmoHint: "当日确认",
    copyBtn: "复制", copiedBtn: "已复制 ✓",
    depositSentCta: "我已转定金", balanceSentCta: "我已转尾款",
    sentHelp: "我们将在 1 个工作日内确认到账并锁定钻石，随后立即邮件通知您。",
    reportedBadge: "确认到账中",
    reportedNote: "已收到您的转账报告。BeloveD 正在确认到账，钻石锁定后会立即邮件通知您。",
    doneBadge: "定金已确认",
    balanceTitle: "尾款支付",
    balanceReportedNote: "谢谢 — 我们会尽快确认尾款并安排发货。",
    nextConfirm: "请查看并确认您的方案。",
    confirmingDeposit: "已报告转账 — BeloveD 正在确认到账。",
    nextBalance: "请支付尾款以完成发货准备。",
  },
  es: {
    journeyRequest: "Solicitud", journeyRequestSub: "Enviada",
    journeyProposal: "Propuesta", journeyProposalSubNow: "Confirma ahora", journeyProposalSubPrep: "En preparación",
    journeyDeposit: "Depósito", journeyDepositSub: "Zelle / Venmo",
    journeyProduction: "Producción", journeyProductionSub: "CAD → Final → Envío",
    proposalKicker: "Tu propuesta",
    preparingTitle: "Estamos preparando tu propuesta.",
    preparingBody: "BeloveD está confirmando una piedra acorde a tus especificaciones y el precio total con nuestros talleres. Normalmente en 24–48 horas revisarás una propuesta aquí.",
    specStone: "Piedra", specGrade: "Grado", specCert: "Certificado", specSetting: "Montura", specLead: "Tiempo de producción",
    specMetal: "Metal", weightApprox: (g) => `≈ ${g} g`, designNote: "Ajuste de diseño",
    pieceTitle: "Tu pieza", priceTitle: "Tu precio",
    totalLabel: "Total, todo incluido",
    totalMeta: "Incluye montura, piedra, trabajo, envío y seguro — sin costos ocultos.",
    depositToday: "Depósito — hoy", balanceShip: "Saldo — antes del envío",
    subTitle: "Sustitución equivalente",
    subBody: "Según disponibilidad, esta piedra puede sustituirse por otra certificada de especificaciones iguales o mejores (±0.03 ct, mismo grado de color/claridad o superior). Si ocurre, primero enviamos el nuevo número IGI y un video, y avanzamos solo con tu OK.",
    confirmCta: "Confirmar esta propuesta", confirmedBadge: "Confirmada",
    payTitle: "Reserva con depósito", payAfter: "Después de confirmar",
    memoLabel: "Nota del pago", memoRequired: "Obligatoria",
    payStep1: "Escanea un QR — o copia el destinatario y envía desde tu app.",
    payStep2: "Pega esta nota con tu pago. Solo podemos confirmar transferencias que incluyan tu número de pedido.",
    payStep3: "¿Ya lo enviaste? Avísanos abajo.",
    copyRecipient: "Copiar destinatario",
    zelleHint: "Sin comisión · confirmación rápida", venmoHint: "Confirmación el mismo día",
    copyBtn: "Copiar", copiedBtn: "Copiado ✓",
    depositSentCta: "Ya envié el depósito", balanceSentCta: "Ya envié el saldo",
    sentHelp: "Confirmamos en 1 día hábil, bloqueamos tu piedra y te avisamos por correo.",
    reportedBadge: "Confirmando transferencia",
    reportedNote: "Pago reportado. BeloveD está confirmando la transferencia — te avisaremos por correo cuando tu piedra quede bloqueada.",
    doneBadge: "Depósito confirmado",
    balanceTitle: "Pago del saldo",
    balanceReportedNote: "Gracias — confirmaremos el saldo en breve y prepararemos el envío.",
    nextConfirm: "Revisa y confirma tu propuesta.",
    confirmingDeposit: "Depósito reportado — BeloveD está confirmando la transferencia.",
    nextBalance: "Envía el saldo para terminar la preparación del envío.",
  },
};
