// Generated by scripts/import_style_csvs.py. Do not edit by hand.
export const styleSeedData = [
  {
    "id": "RING-001",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR09875R400/medium/RIGTXR09875R400-WG-RB-WH-400-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR09875R400/medium/RIGTXR09875R400-WG-RB-WH-400-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR09875R400/medium/RIGTXR09875R400-WG-RB-WH-400-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/4-ctw-round-lab-grown-diamond-solitaire-engagement-ring-platinum/pid/RIGTXR09875R400PL2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Solitaire Ring",
      "ko": "4프롱 솔리테어 링",
      "zh": "四爪单钻戒",
      "es": "Anillo solitario de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-002",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR01745/medium/RIGTXR01745-WG-RB-WH-150-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR01745/medium/RIGTXR01745-WG-RB-WH-150-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR01745/medium/RIGTXR01745-WG-RB-WH-150-M3.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-2-ctw-round-lab-grown-diamond-cathedral-six-prong-solitaire-engagement-ring-platinum/pid/RIGTXR01745-PL2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cathedral Six-Prong Solitaire Ring",
      "ko": "캐시드럴 6프롱 솔리테어 링",
      "zh": "大教堂六爪单钻戒",
      "es": "Anillo solitario catedral de 6 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-003",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGKSR6117R600/medium/RIGKSR6117R600-WG-RB-WH-700-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGKSR6117R600/medium/RIGKSR6117R600-WG-RB-WH-700-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGKSR6117R600/medium/RIGKSR6117R600-WG-RB-WH-700-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/7-ctw-round-lab-grown-diamond-halo-engagement-ring-platinum/pid/RIGKSR6115R600-PL3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Halo Engagement Ring",
      "ko": "라운드 헤일로 약혼반지",
      "zh": "圆形光环订婚戒指",
      "es": "Anillo de compromiso halo redondo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-004",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR03183/medium/RIGTXR03183-GW4_1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR03183/medium/RIGTXR03183-GW4_1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR03183/medium/RIGTXR03183-GW4.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR03183/medium/RIGTXR03183-GW4-1-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR03183/medium/RIGTXR03183-WG-M3.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-1-2-ctw-emerald-lab-grown-diamond-hidden-halo-engagement-ring-14k-white-gold/pid/RIGTXR03183-GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Emerald Hidden Halo Engagement Ring",
      "ko": "에메랄드 히든 헤일로 약혼반지",
      "zh": "祖母绿形隐藏光环订婚戒指",
      "es": "Anillo de compromiso halo oculto esmeralda"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-005",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGJRD0315/medium/RIGJRD0315-HW4_1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGJRD0315/medium/RIGJRD0315-HW4_1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGJRD0315/medium/RIGJRD0315-HW4_2.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGJRD0315/medium/RIGJRD0315-HW4-1-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/4-ctw-round-lab-grown-diamond-three-stone-ring-18k-white-gold/pid/RIGJRD0315HW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Three-Stone Ring",
      "ko": "라운드 쓰리 스톤 링",
      "zh": "圆形三石戒指",
      "es": "Anillo de tres piedras redondas"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-006",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIG0894X4C400H1/medium/RIG0894X4C400H1-GW-NEW.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIG0894X4C400H1/medium/RIG0894X4C400H1-GW-NEW.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/7-ctw-cushion-lab-grown-diamond-double-row-side-stones-halo-engagement-ring-14k-white-gold/pid/RIG0894X4C500H1PL2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cushion Double-Row Side-Stone Halo Ring",
      "ko": "쿠션 더블 로우 사이드 스톤 헤일로 링",
      "zh": "垫形双排侧石光环戒指",
      "es": "Anillo halo cushion con doble fila lateral"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-007",
    "category": "ring",
    "subcategory": "statementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGRVR02048/medium/RIGRVR02048-YG-RB-WH-200-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGRVR02048/medium/RIGRVR02048-YG-RB-WH-200-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGRVR02048/medium/RIGRVR02048-YG-RB-WH-200-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-bold-bezel-solitaire-engagement-ring-14k-yellow-gold/pid/RIGRVR02048-GY2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Bold Bezel Solitaire Ring",
      "ko": "볼드 베젤 솔리테어 링",
      "zh": "宽边包镶单钻戒",
      "es": "Anillo solitario bisel bold"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-009",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTX06263R200/medium/RIGTX06263R200-GW4_1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTX06263R200/medium/RIGTX06263R200-GW4_1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTX06263R200/medium/RIGTX06263R200-GW4_2.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGTXR06263/medium/RIGTXR06263-2.50-GW4-1-NEW.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-low-solitaire-engagement-ring-14k-white-gold/pid/RIGTX06263R200-GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Low Four-Prong Solitaire Ring",
      "ko": "로우 4프롱 솔리테어 링",
      "zh": "低款四爪单钻戒",
      "es": "Anillo solitario bajo de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BAND-001",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGWR4428/medium/RIGWR4428-WG-RB-WH-500-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGWR4428/medium/RIGWR4428-WG-RB-WH-500-M0-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/RIGWR4428/medium/RIGWR4428-WG-RB-WH-500-M1-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGWR4428/medium/BNGWR4428-400GW4-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-shared-prong-round-lab-grown-diamond-eternity-band-14k-white-gold/pid/BNGWR4428-700GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Shared-Prong Diamond Eternity Band",
      "ko": "쉐어드 프롱 다이아 이터니티 밴드",
      "zh": "爪镶排钻",
      "es": "Banda eternity de diamantes compartidos"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BAND-005",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGTXR04267/medium/BNGTXR04267-YG-RB-WH-100-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGTXR04267/medium/BNGTXR04267-YG-RB-WH-100-M0-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGTXR04267/medium/BNGTXR04267-YG-RB-WH-100-M1-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-ctw-round-lab-grown-diamond-french-pave-wedding-band-14k-yellow-gold/pid/BNGTXR04267-GY2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "French Pavé Wedding Band",
      "ko": "프렌치 파베 웨딩 밴드",
      "zh": "戒臂铺小钻",
      "es": "Banda de boda pavé francés"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BAND-006",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGYR1450K/medium/BNGYR1450K-WG-RB-WH-200-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGYR1450K/medium/BNGYR1450K-WG-RB-WH-200-M0-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGYR1450K/medium/BNGYR1450K-WG-RB-WH-200-M1-new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BNGYR1450F/medium/BNGYR1450F-GW4%20-%20BNGYR1450G-GW4%20-%20BNGYR1450K-GW4%20-%20BNGYR1450M-GW4%20E_new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-channel-set-eternity-band-platinum/pid/BNGYR1450K-PL2-700",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Channel-Set Eternity Band",
      "ko": "채널 세트 이터니티 밴드",
      "zh": "槽镶排钻",
      "es": "Banda eternity channel set"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-001",
    "category": "earrings",
    "subcategory": "studs",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE01900/medium/EAGTXE01900-GW3-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE01900/medium/EAGTXE01900-GW3-1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE01900/medium/EAGTXE01900-WG-RB-WH-150-M1-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-2-ctw-round-lab-grown-diamond-stud-earrings-14k-white-gold/pid/EAGTXE01900-GW3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Diamond Stud Earrings",
      "ko": "라운드 다이아몬드 스터드 이어링",
      "zh": "单钻",
      "es": "Aretes de diamantes redondos"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-002",
    "category": "earrings",
    "subcategory": "huggies",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGJOE555/medium/EAGJOE555-GP2-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGJOE555/medium/EAGJOE555-GP2-1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGJOE555/medium/EAGJOE555-GP2-2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/4-ctw-round-lab-grown-diamond-inside-out-hoop-earrings-14k-rose-gold/pid/EAGJOE555-GP2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Inside-Out Hoop Earrings",
      "ko": "인사이드 아웃 후프 이어링",
      "zh": "钻石圈圈耳圈",
      "es": "Aros inside-out"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-003",
    "category": "earrings",
    "subcategory": "studs",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02393/medium/EAGTXE02393-RG-PR-WH-119-M3.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02393/medium/EAGTXE02393-RG-PR-WH-119-M3.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02393/medium/EAGTXE02393-RG-PR-WH-119-M1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/TXE02393/medium/TXE02393-1-GW1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-5-ctw-princess-lab-grown-diamond-halo-stud-earrings-14k-rose-gold/pid/EAGTXE02393-GP3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Princess Halo Stud Earrings",
      "ko": "프린세스 헤일로 스터드 이어링",
      "zh": "主钻+一圈碎钻",
      "es": "Aretes halo princess"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-004",
    "category": "earrings",
    "subcategory": "huggies",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/AJE06021/medium/AJE06021-WG-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/AJE06021/medium/AJE06021-WG-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/AJE06021/medium/AJE06021-WG-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-cushion-lab-grown-diamond-huggie-hoop-earrings-platinum/pid/EAGAJE06021-PL2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cushion Huggie Hoop Earrings",
      "ko": "쿠션 허기 후프 이어링",
      "zh": "贴耳小圈钻",
      "es": "Aros huggie cushion"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-005",
    "category": "earrings",
    "subcategory": "drops",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02083/medium/EAGTXE02083-RG-EM-WH-250-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02083/medium/EAGTXE02083-RG-EM-WH-250-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGTXE02083/medium/EAGTXE02083-RG-EM-WH-250-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-1-2-ctw-emerald-lab-grown-diamond-halo-drop-earrings-14k-rose-gold/pid/EAGTXE02084-GP2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Emerald Halo Drop Earrings",
      "ko": "에메랄드 헤일로 드롭 이어링",
      "zh": "钻坠下来",
      "es": "Aretes colgantes halo esmeralda"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-006",
    "category": "earrings",
    "subcategory": "huggies",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGRVE04056/medium/EAGRVE04056-RG-RB-WH-200-M3.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGRVE04056/medium/EAGRVE04056-RG-RB-WH-200-M3.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EAGRVE04056/medium/EAGRVE04056-RG-RB-WH-200-M1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/EARRVE04056/medium/EARRVE04056-GW4-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-graduated-inside-out-huggie-hoop-earrings-14k-rose-gold/pid/EARRVE04056-GP2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Graduated Inside-Out Huggie Hoop Earrings",
      "ko": "그라데이티드 인사이드 아웃 허기 후프 이어링",
      "zh": "小钻连大钻",
      "es": "Aros huggie inside-out graduados"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-001",
    "category": "bangle",
    "subcategory": "tennisBracelet",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR00769/medium/BCGTXBR00769-YG-RB-WH-1200-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR00769/medium/BCGTXBR00769-YG-RB-WH-1200-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR00769/medium/BCGTXBR00769-YG-RB-WH-1200-M3.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR00769/medium/BCGTXBR00769-GW2-1-NEW.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR00769/medium/BCGTXBR00769-YG-M2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/12-ctw-round-lab-grown-diamond-four-prong-tennis-bracelet-14k-yellow-gold-7-5-inches/pid/BCGTXBR00769-GY2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Tennis Bracelet",
      "ko": "4프롱 테니스 브레이슬릿",
      "zh": "网球手链",
      "es": "Pulsera tenis de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-002",
    "category": "bangle",
    "subcategory": "bangle",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGVG2664K/medium/BCGVG2664K-WG-RB-WH-210-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGVG2664K/medium/BCGVG2664K-WG-RB-WH-210-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGVG2664K/medium/BCGVG2664K-WG-RB-WH-210-M3.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGVG2664K/medium/BCGVG2664K-GW4-1_new.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGVG2664K/medium/BCGVG2664K-WG-M2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-shared-prongs-bangle-bracelet-14k-white-gold-7-inches/pid/BCGVG2664K-GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Shared-Prong Bangle Bracelet",
      "ko": "쉐어드 프롱 뱅글 브레이슬릿",
      "zh": "满钻手镯",
      "es": "Brazalete de garras compartidas"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-003",
    "category": "bangle",
    "subcategory": "tennisBracelet",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR09965/medium/BCGTXBR09965-YG-RB-WH-200-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR09965/medium/BCGTXBR09965-YG-RB-WH-200-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/BCGTXBR09965/medium/BCGTXBR09965-YG-RB-WH-200-M3.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-beveled-x-tennis-bracelet-14k-yellow-gold-7-inches/pid/TXBR09965GY2-2-70",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Beveled X Tennis Bracelet",
      "ko": "베벨드 X 테니스 브레이슬릿",
      "zh": "站点钻手链",
      "es": "Pulsera tenis Beveled X"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-001",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP07660R300/medium/PNGTXP07660R300-WG-RB-WH-300-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP07660R300/medium/PNGTXP07660R300-WG-RB-WH-300-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP07660R300/medium/PNGTXP07660R300-WG-RB-WH-300-M1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP07660R150/medium/PNGTXP07660R150-GW6-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-round-lab-grown-diamond-solitaire-pendant-platinum/pid/PNGTXP07660R300-PL3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Solitaire Pendant",
      "ko": "라운드 솔리테어 펜던트",
      "zh": "单钻",
      "es": "Colgante solitario redondo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-002",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP01957/medium/PNGTXP01957-RG-RB-WH-175-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP01957/medium/PNGTXP01957-RG-RB-WH-175-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP01957/medium/PNGTXP01957-RG-RB-WH-175-M1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGTXP01957/medium/PNGTXP01957-RG-M2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-3-4-ctw-round-lab-grown-diamond-halo-pendant-with-adjustable-chain-14k-rose-gold/pid/PNGTXP01957-GP3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Halo Pendant",
      "ko": "라운드 헤일로 펜던트",
      "zh": "单钻带一圈碎钻",
      "es": "Colgante halo redondo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-003",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://ion.bluenile.com/sets/Jewelry/Photoshoot/Bluenile/Orbitvu/FineJewelry/857162W1404L/857162W1404L_SKU_1_1600X1600.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://ion.bluenile.com/sets/Jewelry/Photoshoot/Bluenile/Orbitvu/FineJewelry/857162W1404L/857162W1404L_SKU_1_1600X1600.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/jewelry/necklaces/cluster-diamond-flower-pendant-necklace-with-1-ctw-round-cut-lab-grown-diamonds-in-14k-white-gold-item-302692?utm_source=google&utm_medium=sem_unbranded_shopping&utm_campaign=semus_bn_google_us_jewelry_labgrownjewelry&utm_term=Lab_Grown_Necklaces&utm_content=666911997034&gad_source=1&gad_campaignid=20393548284&gbraid=0AAAAAD_EjsilRPYWMzhiU0urRrZuL3i6o&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa3t9XcuR6rpiNTADWTAxjq94mLctYRBBGG850eFFPj_QlzJYPnNi0UaAm2_EALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cluster Flower Pendant",
      "ko": "클러스터 플라워 펜던트",
      "zh": "四叶草",
      "es": "Colgante floral cluster"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-004",
    "category": "necklace",
    "subcategory": "stationNecklace",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGRVN01233R500/medium/NCGRVN01233R500-WG-RB-WH-500-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGRVN01233R500/medium/NCGRVN01233R500-WG-RB-WH-500-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-round-lab-grown-diamond-thirteen-stone-demi-eternity-necklace-14k-white-gold/pid/NECRN01233R500-GW2?cq_src=google_ads&cq_cmp=22123575278&cq_con=178662484052&cq_term=&cq_med=pla&cq_plac=&cq_net=g&cq_plt=gp&gad_source=1&gad_campaignid=22123575278&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa3vJ9HK-qt1-kNJTNygGs5lxu8oEQOPCPu8Oc0cUu9fngs0HkEYxvQaAovcEALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Thirteen-Stone Demi Eternity Necklace",
      "ko": "13스톤 데미 이터니티 네크리스",
      "zh": "横向排钻",
      "es": "Collar demi eternity de trece piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-005",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://ion.bluenile.com/sets/Jewelry/Photoshoot/Bluenile/Orbitvu/FineJewelry/857170W14L/857170W14L_SKU_1_1600X1600.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://ion.bluenile.com/sets/Jewelry/Photoshoot/Bluenile/Orbitvu/FineJewelry/857170W14L/857170W14L_SKU_1_1600X1600.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/jewelry/necklaces/diamond-drop-necklace-with-125-ctw-round-and-pear-shaped-lab-grown-diamonds-in-14k-white-gold-item-309201?utm_source=google&utm_medium=sem_unbranded_shopping&utm_campaign=semus_bn_google_us_jewelry_labgrownjewelry&utm_term=Lab_Grown_Necklaces&utm_content=666911997034&gad_source=1&gad_campaignid=20393548284&gbraid=0AAAAAD_EjsilRPYWMzhiU0urRrZuL3i6o&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa2FQc5EygWIe3q_o3M75IZkmKuoouvPKLmjysKE8mvOPy7mqFJtvfEaAvbaEALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round and Pear Diamond Drop Necklace",
      "ko": "라운드 앤 페어 다이아 드롭 네크리스",
      "zh": "小圆钻连大钻",
      "es": "Collar colgante de diamantes redondos y pera"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-006",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://dianamjewels.com/cdn/shop/files/DP2284-2W_f45a16d1-c237-45c6-b77f-74978e8991c0.jpg?v=1764706150&width=1600",
    "media": [
      {
        "kind": "image",
        "src": "https://dianamjewels.com/cdn/shop/files/DP2284-2W_f45a16d1-c237-45c6-b77f-74978e8991c0.jpg?v=1764706150&width=1600"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://dianamjewels.com/products/lab-grown-diamond-marquise-pear-cut-flower-pendant?variant=47022501593188",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Marquise Pear Flower Pendant",
      "ko": "마퀴즈 페어 플라워 펜던트",
      "zh": "蝴蝶大钻",
      "es": "Colgante floral marquise y pera"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-007",
    "category": "necklace",
    "subcategory": "tennisNecklace",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGXK4149Q/medium/NCGXK4149Q-RG-RB-WH-700-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGXK4149Q/medium/NCGXK4149Q-RG-RB-WH-700-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGXK4149Q/medium/NCGXK4149Q-RG-RB-WH-700-M4.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGXK4149Q/medium/NCGXK4149Q-RG-RB-WH-700-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-round-lab-grown-diamond-four-prong-tennis-necklace-14k-rose-gold/pid/NECUDN03480GP2-18",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Tennis Necklace",
      "ko": "4프롱 테니스 네크리스",
      "zh": "网球项链",
      "es": "Collar tenis de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-008",
    "category": "necklace",
    "subcategory": "stationNecklace",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGKN29498/medium/NCGKN29498-WG-RB-WH-200-M0-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGKN29498/medium/NCGKN29498-WG-RB-WH-200-M0-1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGKN29498/medium/NCGKN29498-WG-RB-WH-200-M4.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGKN29498/medium/NCGKN29498-WG-RB-WH-200-M2-1.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NCGKN29498/medium/NCGKN29498-WG-RB-WH-200-M1-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-station-necklace-14k-white-gold/pid/NECKN29498-GW2-16?cq_src=google_ads&cq_cmp=22123575278&cq_con=178662484052&cq_term=&cq_med=pla_with_promotion&cq_plac=&cq_net=g&cq_plt=gp&gad_source=1&gad_campaignid=22123575278&gclid=CjwKCAjwl97RBhBWEiwAa9rbXfkzl0yBNueHp24spA_vTL_zTFZp8rUDss-nkguF0iLgLRjCEY2cORoC_7IQAvD_BwE",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Station Necklace",
      "ko": "스테이션 네크리스",
      "zh": "泡泡链",
      "es": "Collar station"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-009",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGKP0960/medium/PNGKP0960-RG-RB-WH-300-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/PNGKP0960/medium/PNGKP0960-RG-RB-WH-300-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-round-lab-grown-diamond-cross-pendant-with-adjustable-chain-14k-rose-gold/pid/PENKP0960-GP2?algoliaQueryId=0043d09c1b5739ede681cb946715a36a&category_id=41",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Diamond Cross Pendant",
      "ko": "다이아몬드 크로스 펜던트",
      "zh": "十字架",
      "es": "Colgante cruz de diamantes"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-010",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NJOP7967/medium/NJOP7967-WG-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NJOP7967/medium/NJOP7967-WG-M0.jpg"
      },
      {
        "kind": "image",
        "src": "https://media.grownbrilliance.com/a2c5372a-e16a-4ea3-b361-da9fdc89a59f/https://images.grownbrilliance.com/productimages/NJOP7967/medium/NJOP7967-WG-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-2-3-ctw-shield-lab-grown-diamond-cross-statement-pendant-14k-white-gold/pid/PENJOP7967-GW2-18?algoliaQueryId=0043d09c1b5739ede681cb946715a36a&category_id=41",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Shield Diamond Cross Statement Pendant",
      "ko": "쉴드 다이아몬드 크로스 스테이트먼트 펜던트",
      "zh": "十字架 2",
      "es": "Colgante cruz statement con diamante shield"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  }
];
