// Operations Manual 채널 문자열 — 4개 언어

const en = {
  opsMetals: { "14ky": "14K Yellow Gold", "18ky": "18K Yellow Gold", "14kr": "14K Rose Gold", "18kr": "18K Rose Gold", "18kw": "18K White Gold", pt: "Platinum" },
  opsCategories: { ring: "Ring", necklace: "Necklace / Pendant", earrings: "Earrings", bangle: "Bangle / Bracelet" },
  productLines: { solitaire: "Solitaire / Large center stone", multi: "Multi-stone / Pavé" },
  orderStatus: {
    STYLE_SELECTION: "Style selection", STONE_SELECTION: "Stone selection", QUOTATION: "Quotation",
    CAD: "CAD design", PRODUCTION: "In production", QC: "Final QC", BALANCE: "Balance due",
    SHIPPING: "Shipping", DELIVERED: "Delivered", ARCHIVED: "Archived", PAUSED: "Paused", CANCELLED: "Cancelled",
  },
  msStages: {
    depositReceived: "Deposit received", diamondLocked: "Diamond locked", cadIssued: "CAD issued",
    cadApproved: "CAD approved", productionStarted: "Production started", settingPolishing: "Setting / Polishing",
    finalQcVideo: "Final QC video", igiInscriptionVerified: "IGI & inscription verified", actualMetalReconciled: "Actual metal reconciled",
    balanceReceived: "Balance received", sentDomesticWarehouse: "Sent to domestic warehouse", oceanShipment: "Ocean shipment", deliveredArchived: "Delivered & archived",
  },
  msStatus: { pending: "Pending", inProgress: "In progress", waitingClient: "Waiting on you", blocked: "Blocked", done: "Done" },
  stoneEdu: {
    kicker: "Diamond guide",
    shape: {
      title: "Shape",
      body: "The outline of the stone seen from above. Round brilliants deliver maximum sparkle; fancy shapes like oval and pear spread their weight wider, so they face up larger per carat.",
      guide: "Round is the timeless default — oval is the modern pick that wears bigger.",
    },
    carat: {
      title: "Carat weight",
      body: "1 carat = 0.2 g. Face-up size grows slower than weight — a 2 ct round is only about 26% wider than a 1 ct.",
      guide: "Lab-grown pricing makes 1.5–2 ct the sweet spot — sizes that stay rare in mined stones.",
    },
    color: {
      title: "Color grade",
      body: "Graded from D (perfectly colorless) toward Z (warm tint). D–F read colorless; G–J are near-colorless with a hint of warmth from the side.",
      guide: "E reads icy white with no warm tint — our showcase standard.",
    },
    clarity: {
      title: "Clarity grade",
      body: "Counts the inclusions visible under 10× magnification — from IF (internally flawless) down through VVS and VS. VS-grade inclusions are invisible to the naked eye.",
      guide: "VS1 is eye-clean — the value sweet spot before prices jump.",
    },
    growth: {
      title: "Growth method",
      body: "CVD grows the diamond layer by layer in a plasma chamber; HPHT recreates the earth's pressure in a press. Both are real diamonds — identical in hardness, fire, and chemistry.",
      guide: "Above 2 ct we recommend CVD with disclosed post-growth treatment — far better availability.",
    },
    lab: {
      title: "Grading laboratory",
      body: "An independent lab — IGI grades most lab-grown stones — verifies the 4Cs and laser-inscribes the report number on the girdle.",
      guide: "We verify the girdle inscription against your report on video before shipping.",
    },
    fluorescence: {
      title: "Fluorescence",
      body: "How the stone reacts to UV light. None to Faint has no visible effect in daylight; stronger fluorescence can add a hazy cast in sunlight.",
      guide: "Choose None–Faint to keep the icy white look under any light.",
    },
    lwRatio: {
      title: "Length-to-width ratio",
      body: "Length divided by width — it sets the silhouette of fancy shapes. 1.00 is perfectly round; higher numbers stretch the outline.",
      guide: "Classic ovals run 1.30–1.50 — below that reads plump, above reads elongated.",
    },
  },
  intake: {
    title: "Custom Order Request", sub: "Tell us what you want to create. An Order ID and a private tracking code are issued on submission — no payment until you accept the quote.",
    name: "Name", contact: "Email or phone", productLine: "Product line", category: "Category",
    style: "Selected style (from the catalog)", noStyle: "Not decided yet", budget: "Budget ($, optional)", metal: "Metal",
    ringSize: "Ring size (written confirmation required)", chainStyle: "Chain style", chainLength: "Chain length",
    clasp: "Clasp", wristSize: "Wrist size / inner diameter", earringDetails: "Pair matching · post or clip · L/R orientation",
    stoneTitle: "Center stone preferences (solitaire)", morePrefs: "More preferences (optional)",
    shape: "Shape", carat: "Carat", color: "Color", clarity: "Clarity", growth: "Growth method", lab: "Laboratory",
    colorTreatment: "Color-treatment preference", fluorescence: "Fluorescence", lwRatio: "Length-to-width",
    multiTitle: "Multi-stone specification",
    meleeSpec: "Melee specification (size / count)", overallDims: "Overall dimensions",
    arrangement: "Arrangement", multiStandard: "Color / clarity standard",
    bigStoneNote: "Above 2 ct we normally recommend CVD with disclosed post-growth color treatment — stable for everyday wear, with far better availability than untreated stones.",
    requiredDate: "Required date", country: "Delivery country",
    terms: "I accept the terms below", submit: "Submit request",
    doneTitle: "Request received", orderIdLbl: "Your Order ID", codeLbl: "Private tracking code",
    doneNote: "Save this code — it opens your order page without an account. We will reach out within 1 business day.",
    goPortal: "Open my order page",
    termsBlocks: [
      "Minor CAD revisions are allowed after the first design.",
      "Changing style or cancelling after CAD is issued incurs a design fee.",
      "Cancellation after production starts deducts a minimum fee plus unrecoverable loss.",
      "Production is ~10 business days after CAD approval, excluding revisions, holidays, freight, and customs.",
      "Metal weight is estimated and reconciled to the actual finished weight.",
    ],
  },
  styleCat: {
    title: "Style Catalog", sub: "Reproducible styles confirmed with our workshop. Pick one and start a custom order.",
    start: "Start with this style", lead: (d) => `Lead ~${d} business days`, weight: (g) => `Est. metal ${g}g`,
    awaitingMedia: "Awaiting media",
  },
  portal: {
    title: "Order Status", guestTitle: "Track your order", orderId: "Order ID", code: "Tracking code",
    open: "Open", notFound: "Order not found or code incorrect.",
    statusLbl: "Current status", style: "Style", requiredDate: "Required date",
    candidatesTitle: "Your diamond candidates", batchNote: "Candidates are reserved for this order until the batch expiry.",
    select: "Select this stone", selected: "Selected", availability: { available: "Available", hold: "On hold", sold: "Sold" },
    quoteTitle: "Quote", metalAmount: "Metal (est. weight)", packageAmount: "Setting & package", diamondAmount: "Center stone",
    total: "Estimated total", deposit: "Deposit", balance: "Balance", validUntil: "Valid until", lead: (d) => `Production ~${d} business days after CAD approval`,
    accept: "Accept quote & terms", accepted: "Quote accepted",
    cadTitle: "CAD design", cadVersion: (v) => `CAD V${v}`, cadApprove: "Approve", cadRevise: "Request minor revision",
    cadFeedbackPh: "Change 1, Change 2… (contacts/links blocked)", cadMeasure: "Confirm ring size / chain length / dimensions",
    cadDecided: { approved: "Approved", minorRevision: "Minor revision requested", styleChange: "Style change" },
    progressTitle: "Progress", actionsTitle: "Waiting on you", logisticsTitle: "Logistics",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "Color treatment disclosed",
    todo: { diamondSelection: "Choose your center diamond", quoteAcceptance: "Review and accept your quote", cadReview: "Review the CAD design", finalConfirmation: "Confirm the finished piece" },
    phases: { stone: "Stone selected", design: "Design approved", crafting: "Crafting", delivery: "Delivery" },
  },
  supplierP: {
    title: "Supplier Portal", sub: (name) => `${name} — assigned tasks only. Customer identity and selling prices are never shown.`,
    job: "Job", queue: "Task queue", taskTypes: { diamondCandidates: "Diamond candidates", weightLabor: "Metal weight & labor", stockConfirm: "Stock confirmation", cad: "3D CAD", qc: "Final QC files", ship: "Ship to operator" },
    stockTitle: "Is this stone still available?", stockYes: "In stock — hold for this order", stockNo: "Sold out",
    shipTitle: "Submit shipment", trackingNo: "Tracking number", shippedAt: "Ship date",
    briefTitle: "What to make", bCategory: "Item", bMetal: "Metal", bSize: "Size", bStone: "Center stone",
    refLikes: "Customer likes this", changeThis: "Change these points",
    due: "Due", batchUntil: "Batch valid until", required: "Customer required date", styleRef: "Style",
    brief: "Requirements", status: { open: "Open", submitted: "Submitted", closed: "Closed" }, openTask: "Open task", empty: "No tasks.",
    actionsNeeded: (n) => `${n} action${n === 1 ? "" : "s"} needed`, allSubmitted: "All submitted", taskCount: (n) => `${n} task${n === 1 ? "" : "s"}`,
    candTitle: "Submit diamond candidates", addRow: "Add candidate", igiNo: "IGI no.", costUsd: "Cost ($)",
    proportions: "Table / Depth / Crown / Pavilion / L-W / Face-up", media: "Image & video", submit: "Submit",
    wlTitle: "Submit weight & labor", estWeight: "Est. net metal weight (g)", lossIncluded: "Normal production loss included",
    laborUsd: "Labor ($)", meleeUsd: "Melee / materials ($)", leadDays: "Lead time (days)", assumptions: "Assumptions (size, chain, stone dims)",
    cadTitle: "Upload CAD", cadFile: "CAD file / render", qcTitle: "Final QC files", qcVideo: "Front/side/back video", qcCert: "Certificate", qcWeight: "Actual weight evidence (g)",
  },
  visual: {
    parts: { band: "Band", prong: "Prongs", stone: "Center stone", halo: "Halo", gallery: "Gallery", chain: "Chain", clasp: "Clasp", surface: "Surface" },
    refTitle: "Reference photos (optional)",
    refHint: "Show us what you like. Pin a spot and pick a tag — our workshop sees the same pins in their own language. No text needed.",
    refStatus: { pending: "Under review", approved: "Approved", rejected: "Not usable", hidden: "Hidden" },
    pinHint: "Click the image to drop a pin, then choose a tag.",
    addValue: "Target (mm)", removePin: "Remove",
    checkpoint: { stone: "Choose your diamond", design: "Approve the design", final: "Confirm the finished piece" },
    nowAction: "Your turn", upcoming: "Upcoming", doneTag: "Done",
    compareMine: "My style & reference", compareVendor: "Workshop proposal",
    approveCta: "Approve — start production", reviseCta: "Request changes (drop pins)", sendRevision: "Send change request",
    revisionsLeft: (n) => `${n} free revision${n === 1 ? "" : "s"} left`,
    feeNote: (f) => `Further revisions add a $${f} design fee`,
    finalTitle: "Final piece — photos & video",
    finalNotice: "The item in this video is the exact piece that will be shipped to you.",
    finalConfirm: "Confirm — ship my piece", finalConfirmed: "Confirmed — preparing shipment",
    slots: { render360: "360° render", side: "Side view", wear: "On-body / scale" },
    refReviewTitle: "Reference review", approve: "Approve", reject: "Reject",
    chipTitle: "Annotation chips (tap to enable/disable)",
  },
  opsA: {
    menu: { orders: "Order Control", styles: "Style Library", benchmark: "Diamond Pricing", checklist: "Daily Checklist" },
    orders: {
      title: "Orders", owner: "Owner", required: "Required", nextAction: "Open actions", queryCode: "Query code",
      detail: "Workbench", intake: "Intake", internalNotes: "Internal notes (never shown to customer)",
      newPr: "Create procurement request", prType: "Type", supplier: "Supplier", due: "Due date", batchUntil: "Batch valid until", brief: "Brief",
      candidates: "Diamond candidates", review: "Internal review", publish: "Publish", unpublish: "Unpublish",
      custPrice: "Customer price ($)", cost: "Cost", reviews: { recommended: "Recommended", alternate: "Alternate", excluded: "Excluded" },
      lock: "Lock for order", locked: "Locked",
      quoteTitle: "Quote builder", estWeight: "Est. weight (g)", metalRef: "Metal ref ($/g)", lossRate: "Loss rate (%)",
      nonMetal: "Non-metal package ($)", internalCost: "Internal: diamond cost / labor / extras / risk / multiplier",
      createQuote: "Create quote", send: "Send to customer", markDeposit: "Deposit received → CAD",
      actualWeight: "Actual weight (g)", reconcile: "Reconcile balance",
      msTitle: "Milestones", publishClient: "Publish", cadTitle: "CAD reviews", sendCad: "Issue CAD version",
      auditTitle: "Audit log", actionsTitle: "Customer actions", statusSet: "Set status",
      markBalance: "Balance received → ship task", markDelivered: "Received — mark delivered",
      naTitle: "Your next step", naNone: "Nothing to confirm right now — the order is moving automatically.", advanced: "Full detail & manual controls",
      overBudget: "over budget", budgetLabel: "Budget",
      hideRef: "Hide from vendor", showRef: "Restore",
    },
    styles: {
      title: "Style Library", available: "Available for sale", published: "Published", specs: "Specifications",
      newSpec: "Add specification", combo: "Metal + size + center stone", variance: "Variance %", materials: "Materials ($)",
      addStyle: "Add style", leadDays: "Lead (days)", labor: "Labor ($)", estW: "Est. weight (g)",
    },
    bench: { title: "Diamond Benchmark (9 shapes × 7 tiers)", note: "DEF VVS-VS, CVD, post-growth treatment, IGI India — $/ct. Update price and quote date only.", quoted: "Quoted" },
    check: {
      title: "Daily Checklist", waiting: "Waiting-client items", blocked: "Blocked milestones", expiring: "Quotes near expiry",
      lowCand: "Stone-selection orders with <3 published candidates", dueSoon: "Orders near required date", openPr: "Open procurement requests", clear: "All clear",
      depositWait: "Deposits to confirm", balanceWait: "Balances to confirm", held: "Held candidates (not auto-published)",
    },
    monitor: {
      title: "Media feed (vendor ↔ customer)", hide: "Hide", hidden: "Hidden",
      kinds: { reference: "Reference", cad: "CAD", qc: "QC" },
    },
  },
};

const ko = {
  opsMetals: { "14ky": "14K 옐로골드", "18ky": "18K 옐로골드", "14kr": "14K 로즈골드", "18kr": "18K 로즈골드", "18kw": "18K 화이트골드", pt: "플래티넘" },
  opsCategories: { ring: "링", necklace: "네크리스 / 펜던트", earrings: "이어링", bangle: "뱅글 / 브레이슬릿" },
  productLines: { solitaire: "솔리테어 / 대형 센터스톤", multi: "멀티스톤 / 파베" },
  orderStatus: {
    STYLE_SELECTION: "스타일 선택", STONE_SELECTION: "스톤 선택", QUOTATION: "견적", CAD: "CAD 디자인",
    PRODUCTION: "제작중", QC: "최종 QC", BALANCE: "잔금 대기", SHIPPING: "배송중", DELIVERED: "배송완료",
    ARCHIVED: "아카이브", PAUSED: "일시중지", CANCELLED: "취소",
  },
  msStages: {
    depositReceived: "디파짓 수령", diamondLocked: "다이아몬드 확정", cadIssued: "CAD 발행", cadApproved: "CAD 승인",
    productionStarted: "제작 시작", settingPolishing: "세팅/폴리싱", finalQcVideo: "최종 QC 영상",
    igiInscriptionVerified: "IGI·각인 검증", actualMetalReconciled: "실중량 정산", balanceReceived: "잔금 수령",
    sentDomesticWarehouse: "국내 창고 입고", oceanShipment: "해상 운송", deliveredArchived: "배송·아카이브",
  },
  msStatus: { pending: "대기", inProgress: "진행중", waitingClient: "고객 응답 대기", blocked: "차단됨", done: "완료" },
  stoneEdu: {
    kicker: "다이아몬드 가이드",
    shape: {
      title: "셰이프 (모양)",
      body: "위에서 본 스톤의 윤곽입니다. 라운드 브릴리언트는 반짝임이 가장 크고, 오벌·페어 같은 팬시 셰이프는 무게가 넓게 퍼져 같은 캐럿이라도 더 커 보입니다.",
      guide: "고민된다면 라운드가 클래식 — 더 커 보이는 모던한 선택은 오벌입니다.",
    },
    carat: {
      title: "캐럿 (중량)",
      body: "1캐럿 = 0.2g. 정면 크기는 무게보다 천천히 커집니다 — 2캐럿 라운드는 1캐럿보다 지름이 약 26% 클 뿐입니다.",
      guide: "랩그로운 가격대에선 1.5–2캐럿이 스윗 스팟 — 채굴 다이아에선 희귀한 사이즈입니다.",
    },
    color: {
      title: "컬러 (색 등급)",
      body: "D(완전 무색)에서 Z(웜톤)로 갈수록 따뜻한 기운이 더해집니다. D–F는 무색, G–J는 옆에서 볼 때 미세한 온기가 느껴지는 준무색입니다.",
      guide: "E는 따뜻한 기운이 전혀 없는 아이시 화이트 — 저희 쇼케이스 기준입니다.",
    },
    clarity: {
      title: "클래리티 (투명도)",
      body: "10배 확대경으로 보이는 내포물 기준 등급입니다 — IF(내부 무결점)부터 VVS, VS 순서. VS 등급의 내포물은 육안으로 보이지 않습니다.",
      guide: "VS1은 육안 무결점(eye-clean) — 가격이 뛰기 직전의 가성비 스윗 스팟입니다.",
    },
    growth: {
      title: "성장 방식",
      body: "CVD는 플라즈마 챔버에서 층층이 쌓아 올리고, HPHT는 프레스로 지구 내부의 압력을 재현합니다. 둘 다 경도·광채·화학 성분이 동일한 진짜 다이아몬드입니다.",
      guide: "2캐럿 이상은 공시된 성장 후 컬러 처리를 포함한 CVD를 권장합니다 — 수급이 훨씬 좋습니다.",
    },
    lab: {
      title: "감정 기관",
      body: "독립 감정 기관(랩다이아는 대부분 IGI)이 4C를 검증하고 거들에 리포트 번호를 레이저로 각인합니다.",
      guide: "출고 전 거들 각인과 리포트 번호가 일치하는지 영상으로 확인해 드립니다.",
    },
    fluorescence: {
      title: "형광성",
      body: "자외선에 대한 반응입니다. None–Faint는 일상광에서 아무 영향이 없고, 강한 형광은 햇빛 아래에서 뿌연 느낌을 줄 수 있습니다.",
      guide: "어떤 조명에서도 아이시 화이트를 유지하려면 None–Faint를 고르세요.",
    },
    lwRatio: {
      title: "가로세로 비율 (L/W)",
      body: "길이를 너비로 나눈 값으로, 팬시 셰이프의 실루엣을 결정합니다. 1.00은 완전한 원형이고 숫자가 클수록 길쭉해집니다.",
      guide: "클래식 오벌은 1.30–1.50 — 그보다 작으면 통통하게, 크면 길쭉하게 보입니다.",
    },
  },
  intake: {
    title: "주문제작 요청", sub: "원하시는 피스를 알려주세요. 제출 즉시 Order ID와 전용 조회 코드가 발급됩니다 — 견적 수락 전에는 결제가 없습니다.",
    name: "이름", contact: "이메일 또는 연락처", productLine: "제품 라인", category: "카테고리",
    style: "선택한 스타일 (카탈로그에서)", noStyle: "아직 미정", budget: "예산 ($, 선택)", metal: "메탈",
    ringSize: "링 사이즈 (서면 확인 필수)", chainStyle: "체인 스타일", chainLength: "체인 길이",
    clasp: "클라스프", wristSize: "손목 둘레 / 내경", earringDetails: "페어 매칭 · 포스트/클립 · 좌우 구분",
    stoneTitle: "센터스톤 선호 (솔리테어)", morePrefs: "추가 선호 (선택)",
    shape: "쉐입", carat: "캐럿", color: "컬러", clarity: "클래리티", growth: "성장 방식", lab: "감정 기관",
    colorTreatment: "컬러 트리트먼트 선호", fluorescence: "형광", lwRatio: "가로세로 비율",
    multiTitle: "멀티스톤 사양",
    meleeSpec: "멜리 스펙 (사이즈 / 개수)", overallDims: "전체 치수",
    arrangement: "배열", multiStandard: "컬러 / 클래리티 기준",
    bigStoneNote: "2ct 이상은 보통 CVD + 공개된 포스트그로스 컬러 트리트먼트를 권장합니다 — 일상 착용에 안정적이며 미처리 스톤보다 선택지가 훨씬 넓습니다.",
    requiredDate: "필요일", country: "배송 국가",
    terms: "아래 약관에 동의합니다", submit: "요청 제출",
    doneTitle: "요청이 접수되었습니다", orderIdLbl: "Order ID", codeLbl: "전용 조회 코드",
    doneNote: "이 코드를 저장해두세요 — 계정 없이 주문 페이지를 열 수 있습니다. 영업일 1일 내 연락드립니다.",
    goPortal: "내 주문 페이지 열기",
    termsBlocks: [
      "첫 디자인 이후 마이너 CAD 수정은 무료로 허용됩니다.",
      "CAD 발행 후 스타일 변경·취소 시 디자인 수수료가 발생합니다.",
      "제작 시작 후 취소는 최소 수수료 + 회수 불가 손실이 공제됩니다.",
      "제작 기간은 CAD 승인 후 약 10영업일입니다 (수정·연휴·운송·통관 제외).",
      "메탈 중량은 추정치이며 실제 완성 중량으로 정산됩니다.",
    ],
  },
  styleCat: {
    title: "스타일 카탈로그", sub: "공방과 확정된 재현 가능 스타일입니다. 골라서 주문제작을 시작하세요.",
    start: "이 스타일로 시작", lead: (d) => `제작 ~${d}영업일`, weight: (g) => `예상 메탈 ${g}g`,
    awaitingMedia: "미디어 준비중",
  },
  portal: {
    title: "주문 현황", guestTitle: "주문 조회", orderId: "Order ID", code: "조회 코드",
    open: "조회", notFound: "주문이 없거나 코드가 올바르지 않습니다.",
    statusLbl: "현재 상태", style: "스타일", requiredDate: "필요일",
    candidatesTitle: "내 다이아몬드 후보", batchNote: "후보는 배치 만료일까지 이 주문 전용으로 확보됩니다.",
    select: "이 스톤 선택", selected: "선택됨", availability: { available: "구매 가능", hold: "홀드", sold: "판매됨" },
    quoteTitle: "견적", metalAmount: "메탈 (예상 중량)", packageAmount: "세팅·패키지", diamondAmount: "센터스톤",
    total: "예상 합계", deposit: "디파짓", balance: "잔금", validUntil: "유효기한", lead: (d) => `CAD 승인 후 제작 ~${d}영업일`,
    accept: "견적·약관 수락", accepted: "견적 수락됨",
    cadTitle: "CAD 디자인", cadVersion: (v) => `CAD V${v}`, cadApprove: "승인", cadRevise: "마이너 수정 요청",
    cadFeedbackPh: "변경 1, 변경 2… (연락처·링크 자동 차단)", cadMeasure: "링 사이즈 / 체인 길이 / 치수 확인",
    cadDecided: { approved: "승인됨", minorRevision: "마이너 수정 요청됨", styleChange: "스타일 변경" },
    progressTitle: "진행 상황", actionsTitle: "고객 확인 필요", logisticsTitle: "물류",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "컬러 트리트먼트 공개",
    todo: { diamondSelection: "센터 다이아몬드 선택", quoteAcceptance: "견적 확인 후 수락", cadReview: "CAD 디자인 검토", finalConfirmation: "완성품 최종 확인" },
    phases: { stone: "스톤 확정", design: "디자인 승인", crafting: "제작", delivery: "배송" },
  },
  supplierP: {
    title: "서플라이어 포털", sub: (name) => `${name} — 배정된 태스크만 표시됩니다. 고객 신원과 판매가는 절대 노출되지 않습니다.`,
    job: "주문 묶음", queue: "태스크 큐", taskTypes: { diamondCandidates: "다이아 후보", weightLabor: "메탈 중량·공임", stockConfirm: "재고 확인", cad: "3D CAD", qc: "최종 QC 파일", ship: "운영자 배송" },
    stockTitle: "이 스톤 아직 구매 가능한가요?", stockYes: "재고 있음 — 이 주문에 홀드", stockNo: "품절",
    shipTitle: "발송 정보 제출", trackingNo: "운송장 번호", shippedAt: "발송일",
    briefTitle: "제작 내용", bCategory: "품목", bMetal: "메탈", bSize: "사이즈", bStone: "센터스톤",
    refLikes: "고객이 좋아하는 느낌", changeThis: "이 부분을 수정",
    due: "마감", batchUntil: "배치 유효기한", required: "고객 필요일", styleRef: "스타일",
    brief: "요구사항", status: { open: "대기", submitted: "제출됨", closed: "종료" }, openTask: "작업", empty: "태스크가 없습니다.",
    actionsNeeded: (n) => `처리 필요 ${n}건`, allSubmitted: "모두 제출됨", taskCount: (n) => `태스크 ${n}개`,
    candTitle: "다이아 후보 제출", addRow: "후보 추가", igiNo: "IGI 번호", costUsd: "공급가 ($)",
    proportions: "테이블/깊이/크라운/퍼빌리언/비율/페이스업", media: "이미지·영상", submit: "제출",
    wlTitle: "중량·공임 제출", estWeight: "예상 순중량 (g)", lossIncluded: "정상 로스 포함",
    laborUsd: "공임 ($)", meleeUsd: "멜리/부자재 ($)", leadDays: "리드타임 (일)", assumptions: "가정 (사이즈·체인·스톤 치수)",
    cadTitle: "CAD 업로드", cadFile: "CAD 파일/렌더", qcTitle: "최종 QC 파일", qcVideo: "전/측/후면 영상", qcCert: "인증서", qcWeight: "실중량 증빙 (g)",
  },
  visual: {
    parts: { band: "밴드", prong: "프롱", stone: "센터스톤", halo: "헤일로", gallery: "갤러리", chain: "체인", clasp: "클래스프", surface: "표면" },
    refTitle: "레퍼런스 사진 (선택)",
    refHint: "원하는 느낌을 보여주세요. 사진에 핀을 찍고 태그를 고르면 공방은 같은 핀을 자기 언어로 봅니다 — 글이 필요 없습니다.",
    refStatus: { pending: "검수중", approved: "승인됨", rejected: "사용 불가", hidden: "숨김" },
    pinHint: "이미지를 클릭해 핀을 찍고 태그를 선택하세요.",
    addValue: "목표 (mm)", removePin: "삭제",
    checkpoint: { stone: "다이아몬드 선택", design: "디자인 승인", final: "완성품 최종 컨펌" },
    nowAction: "지금 할 일", upcoming: "다음 단계", doneTag: "완료",
    compareMine: "내 스타일 · 레퍼런스", compareVendor: "공방 제안",
    approveCta: "승인 — 제작 시작", reviseCta: "수정 요청 (핀 찍기)", sendRevision: "수정 요청 보내기",
    revisionsLeft: (n) => `무료 수정 ${n}회 남음`,
    feeNote: (f) => `추가 수정부터 디자인비 $${f} 부과`,
    finalTitle: "완성품 사진·영상",
    finalNotice: "이 영상 속 실물이 그대로 배송됩니다.",
    finalConfirm: "컨펌 — 배송 시작", finalConfirmed: "컨펌 완료 — 배송 준비중",
    slots: { render360: "360° 렌더링", side: "측면", wear: "착용/비율" },
    refReviewTitle: "레퍼런스 검수", approve: "승인", reject: "반려",
    chipTitle: "주석 칩 관리 (탭하여 활성/비활성)",
  },
  opsA: {
    menu: { orders: "주문 관제", styles: "스타일 라이브러리", benchmark: "다이아 벤치마크", checklist: "데일리 체크" },
    orders: {
      title: "주문", owner: "오너", required: "필요일", nextAction: "열린 액션", queryCode: "조회 코드",
      detail: "워크벤치", intake: "인테이크", internalNotes: "내부 노트 (고객에게 절대 미노출)",
      newPr: "조달 요청 생성", prType: "유형", supplier: "서플라이어", due: "마감일", batchUntil: "배치 유효기한", brief: "요구사항",
      candidates: "다이아 후보", review: "내부 검수", publish: "공개", unpublish: "비공개",
      custPrice: "고객가 ($)", cost: "원가", reviews: { recommended: "추천", alternate: "대안", excluded: "제외" },
      lock: "주문에 확정", locked: "확정됨",
      quoteTitle: "견적 빌더", estWeight: "예상 중량 (g)", metalRef: "메탈 기준가 ($/g)", lossRate: "로스율 (%)",
      nonMetal: "논메탈 패키지 ($)", internalCost: "내부: 다이아 원가 / 공임 / 부대 / 리스크 / 멀티플라이어",
      createQuote: "견적 생성", send: "고객에게 발송", markDeposit: "디파짓 수령 → CAD",
      actualWeight: "실중량 (g)", reconcile: "잔금 정산",
      msTitle: "마일스톤", publishClient: "고객 공개", cadTitle: "CAD 리뷰", sendCad: "CAD 버전 발행",
      auditTitle: "감사 로그", actionsTitle: "고객 액션", statusSet: "상태 변경",
      markBalance: "잔금 수령 → 배송 태스크", markDelivered: "수령 완료 — 배송 처리",
      naTitle: "지금 할 일", naNone: "지금 확인할 것이 없습니다 — 주문이 자동으로 진행 중입니다.", advanced: "전체 상세 · 수동 제어",
      overBudget: "예산 초과", budgetLabel: "예산",
      hideRef: "벤더에서 숨김", showRef: "복원",
    },
    styles: {
      title: "스타일 라이브러리", available: "판매 가능", published: "공개됨", specs: "스펙",
      newSpec: "스펙 추가", combo: "메탈 + 사이즈 + 센터스톤", variance: "허용 편차 %", materials: "부자재 ($)",
      addStyle: "스타일 추가", leadDays: "리드 (일)", labor: "공임 ($)", estW: "예상 중량 (g)",
    },
    bench: { title: "다이아 벤치마크 (9 쉐입 × 7 티어)", note: "DEF VVS-VS · CVD · 포스트그로스 처리 · IGI India 기준 — $/ct. 단가와 견적일만 갱신하세요.", quoted: "견적일" },
    check: {
      title: "데일리 체크리스트", waiting: "고객 응답 대기", blocked: "차단된 마일스톤", expiring: "만료 임박 견적",
      lowCand: "공개 후보 3개 미만인 스톤선택 주문", dueSoon: "필요일 임박 주문", openPr: "미응답 조달 요청", clear: "모두 정상",
      depositWait: "디파짓 확인 대기", balanceWait: "잔금 확인 대기", held: "보류 후보 (자동 공개 안 됨)",
    },
    monitor: {
      title: "미디어 피드 (벤더 ↔ 고객)", hide: "숨김", hidden: "숨김됨",
      kinds: { reference: "레퍼런스", cad: "CAD", qc: "QC" },
    },
  },
};

const zh = {
  opsMetals: { "14ky": "14K 黄金", "18ky": "18K 黄金", "14kr": "14K 玫瑰金", "18kr": "18K 玫瑰金", "18kw": "18K 白金", pt: "铂金" },
  opsCategories: { ring: "戒指", necklace: "项链 / 吊坠", earrings: "耳环", bangle: "手镯 / 手链" },
  productLines: { solitaire: "单钻 / 大主石", multi: "群镶 / 密镶" },
  orderStatus: {
    STYLE_SELECTION: "款式选择", STONE_SELECTION: "选石", QUOTATION: "报价", CAD: "CAD 设计",
    PRODUCTION: "制作中", QC: "最终质检", BALANCE: "待付尾款", SHIPPING: "运输中", DELIVERED: "已送达",
    ARCHIVED: "已归档", PAUSED: "已暂停", CANCELLED: "已取消",
  },
  msStages: {
    depositReceived: "已收定金", diamondLocked: "钻石锁定", cadIssued: "CAD 已出", cadApproved: "CAD 已批准",
    productionStarted: "开始制作", settingPolishing: "镶嵌/抛光", finalQcVideo: "最终质检视频",
    igiInscriptionVerified: "IGI·镭射码核验", actualMetalReconciled: "实际金重结算", balanceReceived: "已收尾款",
    sentDomesticWarehouse: "入国内仓", oceanShipment: "海运", deliveredArchived: "送达·归档",
  },
  msStatus: { pending: "待处理", inProgress: "进行中", waitingClient: "等待您确认", blocked: "受阻", done: "完成" },
  stoneEdu: {
    kicker: "钻石指南",
    shape: {
      title: "形状",
      body: "从正上方看到的钻石轮廓。圆形明亮式切工火彩最强；椭圆形、梨形等异形钻重量分布更宽，同克拉看起来更大。",
      guide: "经典之选是圆形；想显大又时尚，选椭圆形。",
    },
    carat: {
      title: "克拉（重量）",
      body: "1克拉 = 0.2克。正面尺寸的增长慢于重量——2克拉圆钻的直径只比1克拉大约26%。",
      guide: "以培育钻的价格，1.5–2克拉是甜蜜点——这在天然钻中是稀有尺寸。",
    },
    color: {
      title: "颜色等级",
      body: "从D（完全无色）到Z（暖色调）分级。D–F为无色；G–J为接近无色，侧看略带暖意。",
      guide: "E级呈现冰白色、毫无暖调——这是我们展示库的标准。",
    },
    clarity: {
      title: "净度等级",
      body: "按10倍放大镜下可见的内含物分级——从IF（内部无瑕）到VVS、VS。VS级的内含物肉眼不可见。",
      guide: "VS1肉眼无瑕——是价格跃升前的性价比甜蜜点。",
    },
    growth: {
      title: "生长方式",
      body: "CVD在等离子腔体中逐层生长；HPHT用压机重现地球内部的高压。两者都是真钻石——硬度、火彩、化学成分完全相同。",
      guide: "2克拉以上我们推荐CVD（含披露的生长后处理）——供应充足得多。",
    },
    lab: {
      title: "鉴定机构",
      body: "独立鉴定机构（培育钻大多由IGI鉴定）核实4C，并在腰棱上激光镌刻证书编号。",
      guide: "发货前我们会通过视频核对腰棱镌刻与证书编号一致。",
    },
    fluorescence: {
      title: "荧光",
      body: "钻石对紫外线的反应。None–Faint在日常光线下毫无影响；强荧光在阳光下可能产生雾感。",
      guide: "想在任何光线下保持冰白外观，请选择None–Faint。",
    },
    lwRatio: {
      title: "长宽比",
      body: "长度除以宽度，决定异形钻的轮廓。1.00为正圆，数值越大越修长。",
      guide: "经典椭圆为1.30–1.50——小于则显圆润，大于则显细长。",
    },
  },
  intake: {
    title: "定制订单申请", sub: "告诉我们您想打造的作品。提交后立即生成 Order ID 与专属查询码 — 接受报价前无需付款。",
    name: "姓名", contact: "邮箱或电话", productLine: "产品线", category: "类别",
    style: "已选款式（来自目录）", noStyle: "尚未决定", budget: "预算（$，可选）", metal: "金属",
    ringSize: "戒指尺寸（需书面确认）", chainStyle: "链条款式", chainLength: "链长",
    clasp: "搭扣", wristSize: "腕围 / 内径", earringDetails: "成对匹配 · 耳针/耳夹 · 左右",
    stoneTitle: "主石偏好（单钻）", morePrefs: "更多偏好（可选）",
    shape: "形状", carat: "克拉", color: "颜色", clarity: "净度", growth: "生长方式", lab: "鉴定机构",
    colorTreatment: "色彩处理偏好", fluorescence: "荧光", lwRatio: "长宽比",
    multiTitle: "群镶规格",
    meleeSpec: "配钻规格（尺寸 / 数量）", overallDims: "整体尺寸",
    arrangement: "排列方式", multiStandard: "颜色 / 净度标准",
    bigStoneNote: "2 克拉以上通常建议 CVD + 公开的后期色彩处理 — 日常佩戴稳定，可选范围远大于未处理钻石。",
    requiredDate: "需要日期", country: "收货国家",
    terms: "我接受以下条款", submit: "提交申请",
    doneTitle: "申请已收到", orderIdLbl: "Order ID", codeLbl: "专属查询码",
    doneNote: "请保存此码 — 无需账户即可打开订单页面。我们将在 1 个工作日内联系您。",
    goPortal: "打开我的订单",
    termsBlocks: [
      "首版设计后允许免费小幅 CAD 修改。",
      "CAD 出图后更换款式或取消将收取设计费。",
      "开始制作后取消将扣除最低费用及不可回收损失。",
      "制作周期约为 CAD 批准后 10 个工作日（不含修改、假期、运输与清关）。",
      "金属重量为估算值，按实际成品重量结算。",
    ],
  },
  styleCat: {
    title: "款式目录", sub: "与工坊确认可复刻的款式。选择一款开始定制。",
    start: "用此款式开始", lead: (d) => `制作 ~${d} 个工作日`, weight: (g) => `预估金重 ${g}g`,
    awaitingMedia: "素材准备中",
  },
  portal: {
    title: "订单状态", guestTitle: "查询订单", orderId: "Order ID", code: "查询码",
    open: "查询", notFound: "订单不存在或查询码错误。",
    statusLbl: "当前状态", style: "款式", requiredDate: "需要日期",
    candidatesTitle: "您的钻石候选", batchNote: "候选在批次有效期内为本订单专属保留。",
    select: "选择这颗", selected: "已选择", availability: { available: "可购", hold: "保留中", sold: "已售" },
    quoteTitle: "报价", metalAmount: "金属（预估重量）", packageAmount: "镶嵌·套餐", diamondAmount: "主石",
    total: "预估合计", deposit: "定金", balance: "尾款", validUntil: "有效期至", lead: (d) => `CAD 批准后制作 ~${d} 个工作日`,
    accept: "接受报价与条款", accepted: "已接受报价",
    cadTitle: "CAD 设计", cadVersion: (v) => `CAD V${v}`, cadApprove: "批准", cadRevise: "请求小幅修改",
    cadFeedbackPh: "修改 1、修改 2…（联系方式/链接自动屏蔽）", cadMeasure: "确认戒围 / 链长 / 尺寸",
    cadDecided: { approved: "已批准", minorRevision: "已请求小幅修改", styleChange: "款式变更" },
    progressTitle: "进度", actionsTitle: "等待您确认", logisticsTitle: "物流",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "色彩处理已公开",
    todo: { diamondSelection: "挑选主石", quoteAcceptance: "查看并接受报价", cadReview: "查看 CAD 设计", finalConfirmation: "确认成品" },
    phases: { stone: "选石完成", design: "设计确认", crafting: "制作", delivery: "配送" },
  },
  supplierP: {
    title: "供应商门户", sub: (name) => `${name} — 仅显示分配的任务。绝不显示客户身份与销售价格。`,
    job: "订单组", queue: "任务队列", taskTypes: { diamondCandidates: "钻石候选", weightLabor: "金重·工费", stockConfirm: "库存确认", cad: "3D CAD", qc: "最终质检文件", ship: "发货给运营方" },
    stockTitle: "这颗钻石仍可购买吗？", stockYes: "有货 — 为此订单保留", stockNo: "已售出",
    shipTitle: "提交发货信息", trackingNo: "运单号", shippedAt: "发货日期",
    briefTitle: "制作内容", bCategory: "品类", bMetal: "金属", bSize: "尺寸", bStone: "主石",
    refLikes: "客户喜欢这种感觉", changeThis: "请修改这些地方",
    due: "截止", batchUntil: "批次有效期", required: "客户需要日期", styleRef: "款式",
    brief: "要求", status: { open: "待处理", submitted: "已提交", closed: "已关闭" }, openTask: "处理", empty: "暂无任务。",
    actionsNeeded: (n) => `需处理 ${n} 项`, allSubmitted: "已全部提交", taskCount: (n) => `${n} 个任务`,
    candTitle: "提交钻石候选", addRow: "添加候选", igiNo: "IGI 编号", costUsd: "成本 ($)",
    proportions: "台面/全深/冠部/亭部/长宽比/正面尺寸", media: "图片·视频", submit: "提交",
    wlTitle: "提交金重与工费", estWeight: "预估净金重 (g)", lossIncluded: "已含正常损耗",
    laborUsd: "工费 ($)", meleeUsd: "配钻/辅料 ($)", leadDays: "交期（天）", assumptions: "假设（尺寸·链长·主石尺寸）",
    cadTitle: "上传 CAD", cadFile: "CAD 文件/渲染图", qcTitle: "最终质检文件", qcVideo: "正/侧/背视频", qcCert: "证书", qcWeight: "实际重量证明 (g)",
  },
  visual: {
    parts: { band: "戒臂", prong: "镶爪", stone: "主石", halo: "光环", gallery: "底座", chain: "链条", clasp: "扣环", surface: "表面" },
    refTitle: "参考图（可选）",
    refHint: "把喜欢的感觉拍给我们。在图上钉一个点并选择标签 — 工坊会以自己的语言看到同样的标记，无需文字。",
    refStatus: { pending: "审核中", approved: "已通过", rejected: "不可用", hidden: "已隐藏" },
    pinHint: "点击图片放置图钉，然后选择标签。",
    addValue: "目标 (mm)", removePin: "删除",
    checkpoint: { stone: "挑选钻石", design: "确认设计", final: "确认成品" },
    nowAction: "待您操作", upcoming: "后续步骤", doneTag: "已完成",
    compareMine: "我的款式与参考", compareVendor: "工坊方案",
    approveCta: "通过 — 开始制作", reviseCta: "请求修改（标记图钉）", sendRevision: "发送修改请求",
    revisionsLeft: (n) => `剩余免费修改 ${n} 次`,
    feeNote: (f) => `此后每次修改收取 $${f} 设计费`,
    finalTitle: "成品照片·视频",
    finalNotice: "视频中的实物即为将要发货的成品。",
    finalConfirm: "确认 — 安排发货", finalConfirmed: "已确认 — 备货中",
    slots: { render360: "360° 渲染", side: "侧面", wear: "佩戴/比例" },
    refReviewTitle: "参考图审核", approve: "通过", reject: "驳回",
    chipTitle: "标注标签管理（点按启用/停用）",
  },
  opsA: {
    menu: { orders: "订单管控", styles: "款式库", benchmark: "钻石基准价", checklist: "每日检查" },
    orders: {
      title: "订单", owner: "负责人", required: "需要日期", nextAction: "待办", queryCode: "查询码",
      detail: "工作台", intake: "需求表", internalNotes: "内部备注（绝不向客户展示）",
      newPr: "创建采购任务", prType: "类型", supplier: "供应商", due: "截止日", batchUntil: "批次有效期", brief: "要求",
      candidates: "钻石候选", review: "内部审核", publish: "发布", unpublish: "取消发布",
      custPrice: "客户价 ($)", cost: "成本", reviews: { recommended: "推荐", alternate: "备选", excluded: "排除" },
      lock: "锁定到订单", locked: "已锁定",
      quoteTitle: "报价生成器", estWeight: "预估重量 (g)", metalRef: "金属基准 ($/g)", lossRate: "损耗率 (%)",
      nonMetal: "非金属套餐 ($)", internalCost: "内部：钻石成本 / 工费 / 杂费 / 风险 / 系数",
      createQuote: "创建报价", send: "发送给客户", markDeposit: "已收定金 → CAD",
      actualWeight: "实际重量 (g)", reconcile: "结算尾款",
      msTitle: "里程碑", publishClient: "对客户可见", cadTitle: "CAD 审核", sendCad: "发布 CAD 版本",
      auditTitle: "审计日志", actionsTitle: "客户任务", statusSet: "设置状态",
      markBalance: "已收尾款 → 发货任务", markDelivered: "已收货 — 标记送达",
      naTitle: "下一步", naNone: "目前无需确认 — 订单正在自动推进。", advanced: "完整详情与手动控制",
      overBudget: "超预算", budgetLabel: "预算",
      hideRef: "对供应商隐藏", showRef: "恢复",
    },
    styles: {
      title: "款式库", available: "可售", published: "已发布", specs: "规格",
      newSpec: "新增规格", combo: "金属 + 尺寸 + 主石", variance: "允许偏差 %", materials: "辅料 ($)",
      addStyle: "新增款式", leadDays: "交期（天）", labor: "工费 ($)", estW: "预估重量 (g)",
    },
    bench: { title: "钻石基准价（9 形状 × 7 档）", note: "DEF VVS-VS · CVD · 后期处理 · IGI India — $/ct。仅更新单价与报价日期。", quoted: "报价日" },
    check: {
      title: "每日检查", waiting: "等待客户项", blocked: "受阻里程碑", expiring: "临近过期报价",
      lowCand: "已发布候选 <3 的选石订单", dueSoon: "临近需要日期的订单", openPr: "未响应采购任务", clear: "全部正常",
      depositWait: "待确认定金", balanceWait: "待确认尾款", held: "保留候选（未自动发布）",
    },
    monitor: {
      title: "媒体流（供应商 ↔ 客户）", hide: "隐藏", hidden: "已隐藏",
      kinds: { reference: "参考图", cad: "CAD", qc: "质检" },
    },
  },
};

const es = {
  opsMetals: { "14ky": "Oro amarillo 14K", "18ky": "Oro amarillo 18K", "14kr": "Oro rosa 14K", "18kr": "Oro rosa 18K", "18kw": "Oro blanco 18K", pt: "Platino" },
  opsCategories: { ring: "Anillo", necklace: "Collar / Colgante", earrings: "Aretes", bangle: "Brazalete / Pulsera" },
  productLines: { solitaire: "Solitario / Piedra central grande", multi: "Multipiedra / Pavé" },
  orderStatus: {
    STYLE_SELECTION: "Selección de estilo", STONE_SELECTION: "Selección de piedra", QUOTATION: "Cotización",
    CAD: "Diseño CAD", PRODUCTION: "En producción", QC: "QC final", BALANCE: "Saldo pendiente",
    SHIPPING: "En envío", DELIVERED: "Entregado", ARCHIVED: "Archivado", PAUSED: "Pausado", CANCELLED: "Cancelado",
  },
  msStages: {
    depositReceived: "Depósito recibido", diamondLocked: "Diamante bloqueado", cadIssued: "CAD emitido",
    cadApproved: "CAD aprobado", productionStarted: "Producción iniciada", settingPolishing: "Engaste / Pulido",
    finalQcVideo: "Video QC final", igiInscriptionVerified: "IGI e inscripción verificados", actualMetalReconciled: "Metal real conciliado",
    balanceReceived: "Saldo recibido", sentDomesticWarehouse: "En almacén doméstico", oceanShipment: "Envío marítimo", deliveredArchived: "Entregado y archivado",
  },
  msStatus: { pending: "Pendiente", inProgress: "En curso", waitingClient: "Esperándote", blocked: "Bloqueado", done: "Hecho" },
  stoneEdu: {
    kicker: "Guía del diamante",
    shape: {
      title: "Forma",
      body: "El contorno de la piedra vista desde arriba. El corte brillante redondo ofrece el máximo destello; las formas fantasía como ovalada o pera reparten el peso y se ven más grandes por quilate.",
      guide: "La redonda es el clásico atemporal; la ovalada es la opción moderna que luce más grande.",
    },
    carat: {
      title: "Peso en quilates",
      body: "1 quilate = 0,2 g. El tamaño visible crece más despacio que el peso: un redondo de 2 ct es solo un 26% más ancho que uno de 1 ct.",
      guide: "Con precios de laboratorio, 1,5–2 ct es el punto óptimo: tamaños raros en diamantes de mina.",
    },
    color: {
      title: "Grado de color",
      body: "Se clasifica de D (incoloro perfecto) hacia Z (tono cálido). D–F se ven incoloros; G–J son casi incoloros con un toque cálido visto de lado.",
      guide: "El grado E se ve blanco glacial sin tono cálido: nuestro estándar de vitrina.",
    },
    clarity: {
      title: "Grado de pureza",
      body: "Clasifica las inclusiones visibles con aumento 10×: de IF (internamente impecable) pasando por VVS y VS. Las inclusiones VS son invisibles a simple vista.",
      guide: "VS1 es limpio a la vista: el punto óptimo antes de que el precio se dispare.",
    },
    growth: {
      title: "Método de crecimiento",
      body: "CVD hace crecer el diamante capa a capa en una cámara de plasma; HPHT recrea la presión terrestre en una prensa. Ambos son diamantes reales: idénticos en dureza, fuego y química.",
      guide: "Por encima de 2 ct recomendamos CVD con tratamiento posterior declarado: mucha mejor disponibilidad.",
    },
    lab: {
      title: "Laboratorio certificador",
      body: "Un laboratorio independiente (IGI certifica la mayoría de los diamantes de laboratorio) verifica las 4C y graba con láser el número del informe en el filetín.",
      guide: "Antes del envío verificamos en video que la inscripción coincida con su informe.",
    },
    fluorescence: {
      title: "Fluorescencia",
      body: "La reacción de la piedra a la luz UV. De None a Faint no tiene efecto visible a la luz del día; una fluorescencia fuerte puede dar un aspecto lechoso al sol.",
      guide: "Elija None–Faint para mantener el blanco glacial bajo cualquier luz.",
    },
    lwRatio: {
      title: "Proporción largo-ancho",
      body: "El largo dividido por el ancho define la silueta de las formas fantasía. 1,00 es perfectamente redondo; cifras mayores estilizan el contorno.",
      guide: "Los ovalados clásicos van de 1,30 a 1,50; por debajo se ven rellenos, por encima alargados.",
    },
  },
  intake: {
    title: "Solicitud de Pedido a Medida", sub: "Cuéntanos qué quieres crear. Al enviar se emiten un Order ID y un código privado de seguimiento — sin pago hasta aceptar la cotización.",
    name: "Nombre", contact: "Correo o teléfono", productLine: "Línea de producto", category: "Categoría",
    style: "Estilo elegido (del catálogo)", noStyle: "Aún sin decidir", budget: "Presupuesto ($, opcional)", metal: "Metal",
    ringSize: "Talla de anillo (confirmación escrita requerida)", chainStyle: "Estilo de cadena", chainLength: "Largo de cadena",
    clasp: "Broche", wristSize: "Muñeca / diámetro interno", earringDetails: "Par a juego · poste o clip · izquierda/derecha",
    stoneTitle: "Preferencias de piedra central (solitario)", morePrefs: "Más preferencias (opcional)",
    shape: "Forma", carat: "Quilates", color: "Color", clarity: "Pureza", growth: "Método de crecimiento", lab: "Laboratorio",
    colorTreatment: "Preferencia de tratamiento de color", fluorescence: "Fluorescencia", lwRatio: "Relación largo-ancho",
    multiTitle: "Especificación multipiedra",
    meleeSpec: "Especificación de melee (tamaño / cantidad)", overallDims: "Dimensiones generales",
    arrangement: "Disposición", multiStandard: "Estándar de color / pureza",
    bigStoneNote: "Sobre 2 ct normalmente recomendamos CVD con tratamiento de color divulgado — estable para uso diario y con mucha más disponibilidad.",
    requiredDate: "Fecha requerida", country: "País de entrega",
    terms: "Acepto los términos siguientes", submit: "Enviar solicitud",
    doneTitle: "Solicitud recibida", orderIdLbl: "Tu Order ID", codeLbl: "Código privado de seguimiento",
    doneNote: "Guarda este código — abre tu página de pedido sin cuenta. Te contactaremos en 1 día hábil.",
    goPortal: "Abrir mi pedido",
    termsBlocks: [
      "Se permiten revisiones menores del CAD tras el primer diseño.",
      "Cambiar de estilo o cancelar tras emitirse el CAD genera una tarifa de diseño.",
      "Cancelar tras iniciar producción descuenta una tarifa mínima más pérdidas no recuperables.",
      "La producción toma ~10 días hábiles tras aprobar el CAD (sin contar revisiones, feriados, flete y aduana).",
      "El peso del metal es estimado y se concilia con el peso final real.",
    ],
  },
  styleCat: {
    title: "Catálogo de Estilos", sub: "Estilos reproducibles confirmados con nuestro taller. Elige uno y empieza tu pedido.",
    start: "Empezar con este estilo", lead: (d) => `Producción ~${d} días hábiles`, weight: (g) => `Metal est. ${g}g`,
    awaitingMedia: "Material pendiente",
  },
  portal: {
    title: "Estado del Pedido", guestTitle: "Rastrea tu pedido", orderId: "Order ID", code: "Código",
    open: "Abrir", notFound: "Pedido no encontrado o código incorrecto.",
    statusLbl: "Estado actual", style: "Estilo", requiredDate: "Fecha requerida",
    candidatesTitle: "Tus diamantes candidatos", batchNote: "Los candidatos quedan reservados para este pedido hasta el vencimiento del lote.",
    select: "Elegir esta piedra", selected: "Seleccionado", availability: { available: "Disponible", hold: "Reservado", sold: "Vendido" },
    quoteTitle: "Cotización", metalAmount: "Metal (peso est.)", packageAmount: "Engaste y paquete", diamondAmount: "Piedra central",
    total: "Total estimado", deposit: "Depósito", balance: "Saldo", validUntil: "Válida hasta", lead: (d) => `Producción ~${d} días hábiles tras aprobar el CAD`,
    accept: "Aceptar cotización y términos", accepted: "Cotización aceptada",
    cadTitle: "Diseño CAD", cadVersion: (v) => `CAD V${v}`, cadApprove: "Aprobar", cadRevise: "Pedir revisión menor",
    cadFeedbackPh: "Cambio 1, cambio 2… (contactos/enlaces bloqueados)", cadMeasure: "Confirmar talla / largo de cadena / dimensiones",
    cadDecided: { approved: "Aprobado", minorRevision: "Revisión menor solicitada", styleChange: "Cambio de estilo" },
    progressTitle: "Progreso", actionsTitle: "Esperándote", logisticsTitle: "Logística",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "Tratamiento de color divulgado",
    todo: { diamondSelection: "Elige tu diamante central", quoteAcceptance: "Revisa y acepta tu cotización", cadReview: "Revisa el diseño CAD", finalConfirmation: "Confirma la pieza terminada" },
    phases: { stone: "Piedra elegida", design: "Diseño aprobado", crafting: "Fabricación", delivery: "Entrega" },
  },
  supplierP: {
    title: "Portal del Proveedor", sub: (name) => `${name} — solo tareas asignadas. Nunca se muestran identidad del cliente ni precios de venta.`,
    job: "Trabajo", queue: "Cola de tareas", taskTypes: { diamondCandidates: "Candidatos de diamante", weightLabor: "Peso de metal y mano de obra", stockConfirm: "Confirmación de stock", cad: "CAD 3D", qc: "Archivos de QC final", ship: "Enviar al operador" },
    stockTitle: "¿Esta piedra sigue disponible?", stockYes: "En stock — reservar para este pedido", stockNo: "Agotada",
    shipTitle: "Enviar datos de despacho", trackingNo: "Número de guía", shippedAt: "Fecha de envío",
    briefTitle: "Qué fabricar", bCategory: "Pieza", bMetal: "Metal", bSize: "Talla", bStone: "Piedra central",
    refLikes: "Al cliente le gusta esto", changeThis: "Cambia estos puntos",
    due: "Vence", batchUntil: "Lote válido hasta", required: "Fecha requerida del cliente", styleRef: "Estilo",
    brief: "Requisitos", status: { open: "Abierta", submitted: "Enviada", closed: "Cerrada" }, openTask: "Abrir", empty: "Sin tareas.",
    actionsNeeded: (n) => `${n} acción${n === 1 ? "" : "es"} pendiente${n === 1 ? "" : "s"}`, allSubmitted: "Todo enviado", taskCount: (n) => `${n} tarea${n === 1 ? "" : "s"}`,
    candTitle: "Enviar candidatos", addRow: "Añadir candidato", igiNo: "N.º IGI", costUsd: "Costo ($)",
    proportions: "Mesa/Prof./Corona/Pabellón/L-A/Cara", media: "Imagen y video", submit: "Enviar",
    wlTitle: "Enviar peso y mano de obra", estWeight: "Peso neto est. (g)", lossIncluded: "Incluye merma normal",
    laborUsd: "Mano de obra ($)", meleeUsd: "Melee / materiales ($)", leadDays: "Plazo (días)", assumptions: "Supuestos (talla, cadena, dimensiones)",
    cadTitle: "Subir CAD", cadFile: "Archivo CAD / render", qcTitle: "Archivos QC final", qcVideo: "Video frontal/lateral/trasero", qcCert: "Certificado", qcWeight: "Evidencia de peso real (g)",
  },
  visual: {
    parts: { band: "Banda", prong: "Garras", stone: "Piedra central", halo: "Halo", gallery: "Galería", chain: "Cadena", clasp: "Broche", surface: "Superficie" },
    refTitle: "Fotos de referencia (opcional)",
    refHint: "Muéstranos lo que te gusta. Marca un punto y elige una etiqueta — el taller ve los mismos pines en su idioma. Sin texto.",
    refStatus: { pending: "En revisión", approved: "Aprobada", rejected: "No utilizable", hidden: "Oculta" },
    pinHint: "Haz clic en la imagen para poner un pin y elige una etiqueta.",
    addValue: "Objetivo (mm)", removePin: "Quitar",
    checkpoint: { stone: "Elige tu diamante", design: "Aprueba el diseño", final: "Confirma la pieza terminada" },
    nowAction: "Tu turno", upcoming: "Próximos pasos", doneTag: "Listo",
    compareMine: "Mi estilo y referencia", compareVendor: "Propuesta del taller",
    approveCta: "Aprobar — iniciar producción", reviseCta: "Pedir cambios (poner pines)", sendRevision: "Enviar solicitud de cambios",
    revisionsLeft: (n) => `${n} revisión(es) gratis restante(s)`,
    feeNote: (f) => `Las siguientes revisiones añaden $${f} de tarifa de diseño`,
    finalTitle: "Pieza final — fotos y video",
    finalNotice: "La pieza de este video es exactamente la que se enviará.",
    finalConfirm: "Confirmar — enviar mi pieza", finalConfirmed: "Confirmado — preparando envío",
    slots: { render360: "Render 360°", side: "Vista lateral", wear: "Puesto / escala" },
    refReviewTitle: "Revisión de referencias", approve: "Aprobar", reject: "Rechazar",
    chipTitle: "Etiquetas de anotación (toca para activar/desactivar)",
  },
  opsA: {
    menu: { orders: "Control de Pedidos", styles: "Biblioteca de Estilos", benchmark: "Precios de Diamante", checklist: "Checklist Diario" },
    orders: {
      title: "Pedidos", owner: "Responsable", required: "Requerido", nextAction: "Acciones abiertas", queryCode: "Código",
      detail: "Mesa de trabajo", intake: "Solicitud", internalNotes: "Notas internas (nunca visibles al cliente)",
      newPr: "Crear solicitud de compra", prType: "Tipo", supplier: "Proveedor", due: "Vence", batchUntil: "Lote válido hasta", brief: "Requisitos",
      candidates: "Candidatos", review: "Revisión interna", publish: "Publicar", unpublish: "Despublicar",
      custPrice: "Precio cliente ($)", cost: "Costo", reviews: { recommended: "Recomendado", alternate: "Alternativo", excluded: "Excluido" },
      lock: "Bloquear para el pedido", locked: "Bloqueado",
      quoteTitle: "Generador de cotización", estWeight: "Peso est. (g)", metalRef: "Ref. metal ($/g)", lossRate: "Merma (%)",
      nonMetal: "Paquete no metálico ($)", internalCost: "Interno: costo diamante / mano de obra / extras / riesgo / multiplicador",
      createQuote: "Crear cotización", send: "Enviar al cliente", markDeposit: "Depósito recibido → CAD",
      actualWeight: "Peso real (g)", reconcile: "Conciliar saldo",
      msTitle: "Hitos", publishClient: "Visible al cliente", cadTitle: "Revisiones CAD", sendCad: "Emitir versión CAD",
      auditTitle: "Registro de auditoría", actionsTitle: "Acciones del cliente", statusSet: "Cambiar estado",
      markBalance: "Saldo recibido → tarea de envío", markDelivered: "Recibido — marcar entregado",
      naTitle: "Tu siguiente paso", naNone: "Nada que confirmar ahora — el pedido avanza automáticamente.", advanced: "Detalle completo y controles manuales",
      overBudget: "sobre presupuesto", budgetLabel: "Presupuesto",
      hideRef: "Ocultar al proveedor", showRef: "Restaurar",
    },
    styles: {
      title: "Biblioteca de Estilos", available: "A la venta", published: "Publicado", specs: "Especificaciones",
      newSpec: "Añadir especificación", combo: "Metal + talla + piedra central", variance: "Variación %", materials: "Materiales ($)",
      addStyle: "Añadir estilo", leadDays: "Plazo (días)", labor: "Mano de obra ($)", estW: "Peso est. (g)",
    },
    bench: { title: "Benchmark de Diamantes (9 formas × 7 rangos)", note: "DEF VVS-VS · CVD · tratamiento posterior · IGI India — $/ct. Actualiza solo precio y fecha.", quoted: "Cotizado" },
    check: {
      title: "Checklist Diario", waiting: "Esperando al cliente", blocked: "Hitos bloqueados", expiring: "Cotizaciones por vencer",
      lowCand: "Pedidos en selección con <3 candidatos publicados", dueSoon: "Pedidos cerca de la fecha requerida", openPr: "Solicitudes de compra abiertas", clear: "Todo en orden",
      depositWait: "Depósitos por confirmar", balanceWait: "Saldos por confirmar", held: "Candidatos retenidos (sin publicación automática)",
    },
    monitor: {
      title: "Feed de medios (taller ↔ cliente)", hide: "Ocultar", hidden: "Oculto",
      kinds: { reference: "Referencia", cad: "CAD", qc: "QC" },
    },
  },
};

export const opsStrings = { en, ko, zh, es };
