// Operations Manual 채널 문자열 — 4개 언어

const en = {
  opsMetals: { "14ky": "14K Yellow Gold", "18ky": "18K Yellow Gold", "14kr": "14K Rose Gold", "18kr": "18K Rose Gold", "18kw": "18K White Gold", pt: "Platinum" },
  opsCategories: { ring: "Ring", necklace: "Necklace / Pendant", earrings: "Earrings", bangle: "Bangle / Bracelet" },
  productLines: { solitaire: "Solitaire / Large center stone", multi: "Multi-stone / Pavé" },
  orderStatus: {
    STYLE_SELECTION: "Style selection", STONE_SELECTION: "Stone selection", QUOTATION: "Quotation",
    CAD: "CAD design", PRODUCTION: "In production", QC: "Final QC", BALANCE: "Balance due",
    SHIPPING: "Shipping", DELIVERED: "Delivered", ARCHIVED: "Archived", PAUSED: "Paused", CANCELLED: "Cancelled",
  },
  msStages: {
    depositReceived: "Deposit received", diamondLocked: "Diamond locked", cadIssued: "CAD issued",
    cadApproved: "CAD approved", productionStarted: "Production started", settingPolishing: "Setting / Polishing",
    finalQcVideo: "Final QC video", igiInscriptionVerified: "IGI & inscription verified", actualMetalReconciled: "Actual metal reconciled",
    balanceReceived: "Balance received", sentDomesticWarehouse: "Sent to domestic warehouse", oceanShipment: "Ocean shipment", deliveredArchived: "Delivered & archived",
  },
  msStatus: { pending: "Pending", inProgress: "In progress", waitingClient: "Waiting on you", blocked: "Blocked", done: "Done" },
  intake: {
    title: "Custom Order Request", sub: "Tell us what you want to create. An Order ID and a private tracking code are issued on submission — no payment until you accept the quote.",
    name: "Name", contact: "Email or phone", productLine: "Product line", category: "Category",
    style: "Selected style (from the catalog)", noStyle: "Not decided yet", budget: "Budget ($, optional)", metal: "Metal",
    ringSize: "Ring size (written confirmation required)", chainStyle: "Chain style", chainLength: "Chain length",
    clasp: "Clasp", wristSize: "Wrist size / inner diameter", earringDetails: "Pair matching · post or clip · L/R orientation",
    stoneTitle: "Center stone preferences (solitaire)",
    shape: "Shape", carat: "Carat", color: "Color", clarity: "Clarity", growth: "Growth method", lab: "Laboratory",
    colorTreatment: "Color-treatment preference", fluorescence: "Fluorescence", lwRatio: "Length-to-width",
    multiTitle: "Multi-stone specification",
    meleeSpec: "Melee specification (size / count)", overallDims: "Overall dimensions",
    arrangement: "Arrangement", multiStandard: "Color / clarity standard",
    bigStoneNote: "Above 2 ct we normally recommend CVD with disclosed post-growth color treatment — stable for everyday wear, with far better availability than untreated stones.",
    requiredDate: "Required date", country: "Delivery country",
    terms: "I accept the terms below", submit: "Submit request",
    doneTitle: "Request received", orderIdLbl: "Your Order ID", codeLbl: "Private tracking code",
    doneNote: "Save this code — it opens your order page without an account. We will reach out within 1 business day.",
    goPortal: "Open my order page",
    termsBlocks: [
      "Minor CAD revisions are allowed after the first design.",
      "Changing style or cancelling after CAD is issued incurs a design fee.",
      "Cancellation after production starts deducts a minimum fee plus unrecoverable loss.",
      "Production is ~10 business days after CAD approval, excluding revisions, holidays, freight, and customs.",
      "Metal weight is estimated and reconciled to the actual finished weight.",
    ],
  },
  styleCat: {
    title: "Style Catalog", sub: "Reproducible styles confirmed with our workshop. Pick one and start a custom order.",
    start: "Start with this style", lead: (d) => `Lead ~${d} business days`, weight: (g) => `Est. metal ${g}g`,
    awaitingMedia: "Awaiting media",
  },
  portal: {
    title: "Order Status", guestTitle: "Track your order", orderId: "Order ID", code: "Tracking code",
    open: "Open", notFound: "Order not found or code incorrect.",
    statusLbl: "Current status", style: "Style", requiredDate: "Required date",
    candidatesTitle: "Your diamond candidates", batchNote: "Candidates are reserved for this order until the batch expiry.",
    select: "Select this stone", selected: "Selected", availability: { available: "Available", hold: "On hold", sold: "Sold" },
    quoteTitle: "Quote", metalAmount: "Metal (est. weight)", packageAmount: "Setting & package", diamondAmount: "Center stone",
    total: "Estimated total", deposit: "Deposit", balance: "Balance", validUntil: "Valid until", lead: (d) => `Production ~${d} business days after CAD approval`,
    accept: "Accept quote & terms", accepted: "Quote accepted",
    cadTitle: "CAD design", cadVersion: (v) => `CAD V${v}`, cadApprove: "Approve", cadRevise: "Request minor revision",
    cadFeedbackPh: "Change 1, Change 2… (contacts/links blocked)", cadMeasure: "Confirm ring size / chain length / dimensions",
    cadDecided: { approved: "Approved", minorRevision: "Minor revision requested", styleChange: "Style change" },
    progressTitle: "Progress", actionsTitle: "Waiting on you", logisticsTitle: "Logistics",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "Color treatment disclosed",
  },
  supplierP: {
    title: "Supplier Portal", sub: (name) => `${name} — assigned tasks only. Customer identity and selling prices are never shown.`,
    queue: "Task queue", taskTypes: { diamondCandidates: "Diamond candidates", weightLabor: "Metal weight & labor", cad: "3D CAD", qc: "Final QC files" },
    due: "Due", batchUntil: "Batch valid until", required: "Customer required date", styleRef: "Style",
    brief: "Requirements", status: { open: "Open", submitted: "Submitted", closed: "Closed" }, openTask: "Open task", empty: "No tasks.",
    candTitle: "Submit diamond candidates", addRow: "Add candidate", igiNo: "IGI no.", costUsd: "Cost ($)",
    proportions: "Table / Depth / Crown / Pavilion / L-W / Face-up", media: "Image & video", submit: "Submit",
    wlTitle: "Submit weight & labor", estWeight: "Est. net metal weight (g)", lossIncluded: "Normal production loss included",
    laborUsd: "Labor ($)", meleeUsd: "Melee / materials ($)", leadDays: "Lead time (days)", assumptions: "Assumptions (size, chain, stone dims)",
    cadTitle: "Upload CAD", cadFile: "CAD file / render", qcTitle: "Final QC files", qcVideo: "Front/side/back video", qcCert: "Certificate", qcWeight: "Actual weight evidence (g)",
  },
  opsA: {
    menu: { orders: "Order Control", styles: "Style Library", benchmark: "Diamond Pricing", checklist: "Daily Checklist" },
    orders: {
      title: "Orders", owner: "Owner", required: "Required", nextAction: "Open actions", queryCode: "Query code",
      detail: "Workbench", intake: "Intake", internalNotes: "Internal notes (never shown to customer)",
      newPr: "Create procurement request", prType: "Type", supplier: "Supplier", due: "Due date", batchUntil: "Batch valid until", brief: "Brief",
      candidates: "Diamond candidates", review: "Internal review", publish: "Publish", unpublish: "Unpublish",
      custPrice: "Customer price ($)", cost: "Cost", reviews: { recommended: "Recommended", alternate: "Alternate", excluded: "Excluded" },
      lock: "Lock for order", locked: "Locked",
      quoteTitle: "Quote builder", estWeight: "Est. weight (g)", metalRef: "Metal ref ($/g)", lossRate: "Loss rate (%)",
      nonMetal: "Non-metal package ($)", internalCost: "Internal: diamond cost / labor / extras / risk / multiplier",
      createQuote: "Create quote", send: "Send to customer", markDeposit: "Deposit received → CAD",
      actualWeight: "Actual weight (g)", reconcile: "Reconcile balance",
      msTitle: "Milestones", publishClient: "Publish", cadTitle: "CAD reviews", sendCad: "Issue CAD version",
      auditTitle: "Audit log", actionsTitle: "Customer actions", statusSet: "Set status",
    },
    styles: {
      title: "Style Library", available: "Available for sale", published: "Published", specs: "Specifications",
      newSpec: "Add specification", combo: "Metal + size + center stone", variance: "Variance %", materials: "Materials ($)",
      addStyle: "Add style", leadDays: "Lead (days)", labor: "Labor ($)", estW: "Est. weight (g)",
    },
    bench: { title: "Diamond Benchmark (9 shapes × 7 tiers)", note: "DEF VVS-VS, CVD, post-growth treatment, IGI India — $/ct. Update price and quote date only.", quoted: "Quoted" },
    check: {
      title: "Daily Checklist", waiting: "Waiting-client items", blocked: "Blocked milestones", expiring: "Quotes near expiry",
      lowCand: "Stone-selection orders with <3 published candidates", dueSoon: "Orders near required date", openPr: "Open procurement requests", clear: "All clear",
    },
  },
};

const ko = {
  opsMetals: { "14ky": "14K 옐로골드", "18ky": "18K 옐로골드", "14kr": "14K 로즈골드", "18kr": "18K 로즈골드", "18kw": "18K 화이트골드", pt: "플래티넘" },
  opsCategories: { ring: "링", necklace: "네크리스 / 펜던트", earrings: "이어링", bangle: "뱅글 / 브레이슬릿" },
  productLines: { solitaire: "솔리테어 / 대형 센터스톤", multi: "멀티스톤 / 파베" },
  orderStatus: {
    STYLE_SELECTION: "스타일 선택", STONE_SELECTION: "스톤 선택", QUOTATION: "견적", CAD: "CAD 디자인",
    PRODUCTION: "제작중", QC: "최종 QC", BALANCE: "잔금 대기", SHIPPING: "배송중", DELIVERED: "배송완료",
    ARCHIVED: "아카이브", PAUSED: "일시중지", CANCELLED: "취소",
  },
  msStages: {
    depositReceived: "디파짓 수령", diamondLocked: "다이아몬드 확정", cadIssued: "CAD 발행", cadApproved: "CAD 승인",
    productionStarted: "제작 시작", settingPolishing: "세팅/폴리싱", finalQcVideo: "최종 QC 영상",
    igiInscriptionVerified: "IGI·각인 검증", actualMetalReconciled: "실중량 정산", balanceReceived: "잔금 수령",
    sentDomesticWarehouse: "국내 창고 입고", oceanShipment: "해상 운송", deliveredArchived: "배송·아카이브",
  },
  msStatus: { pending: "대기", inProgress: "진행중", waitingClient: "고객 응답 대기", blocked: "차단됨", done: "완료" },
  intake: {
    title: "주문제작 요청", sub: "원하시는 피스를 알려주세요. 제출 즉시 Order ID와 전용 조회 코드가 발급됩니다 — 견적 수락 전에는 결제가 없습니다.",
    name: "이름", contact: "이메일 또는 연락처", productLine: "제품 라인", category: "카테고리",
    style: "선택한 스타일 (카탈로그에서)", noStyle: "아직 미정", budget: "예산 ($, 선택)", metal: "메탈",
    ringSize: "링 사이즈 (서면 확인 필수)", chainStyle: "체인 스타일", chainLength: "체인 길이",
    clasp: "클라스프", wristSize: "손목 둘레 / 내경", earringDetails: "페어 매칭 · 포스트/클립 · 좌우 구분",
    stoneTitle: "센터스톤 선호 (솔리테어)",
    shape: "쉐입", carat: "캐럿", color: "컬러", clarity: "클래리티", growth: "성장 방식", lab: "감정 기관",
    colorTreatment: "컬러 트리트먼트 선호", fluorescence: "형광", lwRatio: "가로세로 비율",
    multiTitle: "멀티스톤 사양",
    meleeSpec: "멜리 스펙 (사이즈 / 개수)", overallDims: "전체 치수",
    arrangement: "배열", multiStandard: "컬러 / 클래리티 기준",
    bigStoneNote: "2ct 이상은 보통 CVD + 공개된 포스트그로스 컬러 트리트먼트를 권장합니다 — 일상 착용에 안정적이며 미처리 스톤보다 선택지가 훨씬 넓습니다.",
    requiredDate: "필요일", country: "배송 국가",
    terms: "아래 약관에 동의합니다", submit: "요청 제출",
    doneTitle: "요청이 접수되었습니다", orderIdLbl: "Order ID", codeLbl: "전용 조회 코드",
    doneNote: "이 코드를 저장해두세요 — 계정 없이 주문 페이지를 열 수 있습니다. 영업일 1일 내 연락드립니다.",
    goPortal: "내 주문 페이지 열기",
    termsBlocks: [
      "첫 디자인 이후 마이너 CAD 수정은 무료로 허용됩니다.",
      "CAD 발행 후 스타일 변경·취소 시 디자인 수수료가 발생합니다.",
      "제작 시작 후 취소는 최소 수수료 + 회수 불가 손실이 공제됩니다.",
      "제작 기간은 CAD 승인 후 약 10영업일입니다 (수정·연휴·운송·통관 제외).",
      "메탈 중량은 추정치이며 실제 완성 중량으로 정산됩니다.",
    ],
  },
  styleCat: {
    title: "스타일 카탈로그", sub: "공방과 확정된 재현 가능 스타일입니다. 골라서 주문제작을 시작하세요.",
    start: "이 스타일로 시작", lead: (d) => `제작 ~${d}영업일`, weight: (g) => `예상 메탈 ${g}g`,
    awaitingMedia: "미디어 준비중",
  },
  portal: {
    title: "주문 현황", guestTitle: "주문 조회", orderId: "Order ID", code: "조회 코드",
    open: "조회", notFound: "주문이 없거나 코드가 올바르지 않습니다.",
    statusLbl: "현재 상태", style: "스타일", requiredDate: "필요일",
    candidatesTitle: "내 다이아몬드 후보", batchNote: "후보는 배치 만료일까지 이 주문 전용으로 확보됩니다.",
    select: "이 스톤 선택", selected: "선택됨", availability: { available: "구매 가능", hold: "홀드", sold: "판매됨" },
    quoteTitle: "견적", metalAmount: "메탈 (예상 중량)", packageAmount: "세팅·패키지", diamondAmount: "센터스톤",
    total: "예상 합계", deposit: "디파짓", balance: "잔금", validUntil: "유효기한", lead: (d) => `CAD 승인 후 제작 ~${d}영업일`,
    accept: "견적·약관 수락", accepted: "견적 수락됨",
    cadTitle: "CAD 디자인", cadVersion: (v) => `CAD V${v}`, cadApprove: "승인", cadRevise: "마이너 수정 요청",
    cadFeedbackPh: "변경 1, 변경 2… (연락처·링크 자동 차단)", cadMeasure: "링 사이즈 / 체인 길이 / 치수 확인",
    cadDecided: { approved: "승인됨", minorRevision: "마이너 수정 요청됨", styleChange: "스타일 변경" },
    progressTitle: "진행 상황", actionsTitle: "고객 확인 필요", logisticsTitle: "물류",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "컬러 트리트먼트 공개",
  },
  supplierP: {
    title: "서플라이어 포털", sub: (name) => `${name} — 배정된 태스크만 표시됩니다. 고객 신원과 판매가는 절대 노출되지 않습니다.`,
    queue: "태스크 큐", taskTypes: { diamondCandidates: "다이아 후보", weightLabor: "메탈 중량·공임", cad: "3D CAD", qc: "최종 QC 파일" },
    due: "마감", batchUntil: "배치 유효기한", required: "고객 필요일", styleRef: "스타일",
    brief: "요구사항", status: { open: "대기", submitted: "제출됨", closed: "종료" }, openTask: "작업", empty: "태스크가 없습니다.",
    candTitle: "다이아 후보 제출", addRow: "후보 추가", igiNo: "IGI 번호", costUsd: "공급가 ($)",
    proportions: "테이블/깊이/크라운/퍼빌리언/비율/페이스업", media: "이미지·영상", submit: "제출",
    wlTitle: "중량·공임 제출", estWeight: "예상 순중량 (g)", lossIncluded: "정상 로스 포함",
    laborUsd: "공임 ($)", meleeUsd: "멜리/부자재 ($)", leadDays: "리드타임 (일)", assumptions: "가정 (사이즈·체인·스톤 치수)",
    cadTitle: "CAD 업로드", cadFile: "CAD 파일/렌더", qcTitle: "최종 QC 파일", qcVideo: "전/측/후면 영상", qcCert: "인증서", qcWeight: "실중량 증빙 (g)",
  },
  opsA: {
    menu: { orders: "주문 관제", styles: "스타일 라이브러리", benchmark: "다이아 벤치마크", checklist: "데일리 체크" },
    orders: {
      title: "주문", owner: "오너", required: "필요일", nextAction: "열린 액션", queryCode: "조회 코드",
      detail: "워크벤치", intake: "인테이크", internalNotes: "내부 노트 (고객에게 절대 미노출)",
      newPr: "조달 요청 생성", prType: "유형", supplier: "서플라이어", due: "마감일", batchUntil: "배치 유효기한", brief: "요구사항",
      candidates: "다이아 후보", review: "내부 검수", publish: "공개", unpublish: "비공개",
      custPrice: "고객가 ($)", cost: "원가", reviews: { recommended: "추천", alternate: "대안", excluded: "제외" },
      lock: "주문에 확정", locked: "확정됨",
      quoteTitle: "견적 빌더", estWeight: "예상 중량 (g)", metalRef: "메탈 기준가 ($/g)", lossRate: "로스율 (%)",
      nonMetal: "논메탈 패키지 ($)", internalCost: "내부: 다이아 원가 / 공임 / 부대 / 리스크 / 멀티플라이어",
      createQuote: "견적 생성", send: "고객에게 발송", markDeposit: "디파짓 수령 → CAD",
      actualWeight: "실중량 (g)", reconcile: "잔금 정산",
      msTitle: "마일스톤", publishClient: "고객 공개", cadTitle: "CAD 리뷰", sendCad: "CAD 버전 발행",
      auditTitle: "감사 로그", actionsTitle: "고객 액션", statusSet: "상태 변경",
    },
    styles: {
      title: "스타일 라이브러리", available: "판매 가능", published: "공개됨", specs: "스펙",
      newSpec: "스펙 추가", combo: "메탈 + 사이즈 + 센터스톤", variance: "허용 편차 %", materials: "부자재 ($)",
      addStyle: "스타일 추가", leadDays: "리드 (일)", labor: "공임 ($)", estW: "예상 중량 (g)",
    },
    bench: { title: "다이아 벤치마크 (9 쉐입 × 7 티어)", note: "DEF VVS-VS · CVD · 포스트그로스 처리 · IGI India 기준 — $/ct. 단가와 견적일만 갱신하세요.", quoted: "견적일" },
    check: {
      title: "데일리 체크리스트", waiting: "고객 응답 대기", blocked: "차단된 마일스톤", expiring: "만료 임박 견적",
      lowCand: "공개 후보 3개 미만인 스톤선택 주문", dueSoon: "필요일 임박 주문", openPr: "미응답 조달 요청", clear: "모두 정상",
    },
  },
};

const zh = {
  opsMetals: { "14ky": "14K 黄金", "18ky": "18K 黄金", "14kr": "14K 玫瑰金", "18kr": "18K 玫瑰金", "18kw": "18K 白金", pt: "铂金" },
  opsCategories: { ring: "戒指", necklace: "项链 / 吊坠", earrings: "耳环", bangle: "手镯 / 手链" },
  productLines: { solitaire: "单钻 / 大主石", multi: "群镶 / 密镶" },
  orderStatus: {
    STYLE_SELECTION: "款式选择", STONE_SELECTION: "选石", QUOTATION: "报价", CAD: "CAD 设计",
    PRODUCTION: "制作中", QC: "最终质检", BALANCE: "待付尾款", SHIPPING: "运输中", DELIVERED: "已送达",
    ARCHIVED: "已归档", PAUSED: "已暂停", CANCELLED: "已取消",
  },
  msStages: {
    depositReceived: "已收定金", diamondLocked: "钻石锁定", cadIssued: "CAD 已出", cadApproved: "CAD 已批准",
    productionStarted: "开始制作", settingPolishing: "镶嵌/抛光", finalQcVideo: "最终质检视频",
    igiInscriptionVerified: "IGI·镭射码核验", actualMetalReconciled: "实际金重结算", balanceReceived: "已收尾款",
    sentDomesticWarehouse: "入国内仓", oceanShipment: "海运", deliveredArchived: "送达·归档",
  },
  msStatus: { pending: "待处理", inProgress: "进行中", waitingClient: "等待您确认", blocked: "受阻", done: "完成" },
  intake: {
    title: "定制订单申请", sub: "告诉我们您想打造的作品。提交后立即生成 Order ID 与专属查询码 — 接受报价前无需付款。",
    name: "姓名", contact: "邮箱或电话", productLine: "产品线", category: "类别",
    style: "已选款式（来自目录）", noStyle: "尚未决定", budget: "预算（$，可选）", metal: "金属",
    ringSize: "戒指尺寸（需书面确认）", chainStyle: "链条款式", chainLength: "链长",
    clasp: "搭扣", wristSize: "腕围 / 内径", earringDetails: "成对匹配 · 耳针/耳夹 · 左右",
    stoneTitle: "主石偏好（单钻）",
    shape: "形状", carat: "克拉", color: "颜色", clarity: "净度", growth: "生长方式", lab: "鉴定机构",
    colorTreatment: "色彩处理偏好", fluorescence: "荧光", lwRatio: "长宽比",
    multiTitle: "群镶规格",
    meleeSpec: "配钻规格（尺寸 / 数量）", overallDims: "整体尺寸",
    arrangement: "排列方式", multiStandard: "颜色 / 净度标准",
    bigStoneNote: "2 克拉以上通常建议 CVD + 公开的后期色彩处理 — 日常佩戴稳定，可选范围远大于未处理钻石。",
    requiredDate: "需要日期", country: "收货国家",
    terms: "我接受以下条款", submit: "提交申请",
    doneTitle: "申请已收到", orderIdLbl: "Order ID", codeLbl: "专属查询码",
    doneNote: "请保存此码 — 无需账户即可打开订单页面。我们将在 1 个工作日内联系您。",
    goPortal: "打开我的订单",
    termsBlocks: [
      "首版设计后允许免费小幅 CAD 修改。",
      "CAD 出图后更换款式或取消将收取设计费。",
      "开始制作后取消将扣除最低费用及不可回收损失。",
      "制作周期约为 CAD 批准后 10 个工作日（不含修改、假期、运输与清关）。",
      "金属重量为估算值，按实际成品重量结算。",
    ],
  },
  styleCat: {
    title: "款式目录", sub: "与工坊确认可复刻的款式。选择一款开始定制。",
    start: "用此款式开始", lead: (d) => `制作 ~${d} 个工作日`, weight: (g) => `预估金重 ${g}g`,
    awaitingMedia: "素材准备中",
  },
  portal: {
    title: "订单状态", guestTitle: "查询订单", orderId: "Order ID", code: "查询码",
    open: "查询", notFound: "订单不存在或查询码错误。",
    statusLbl: "当前状态", style: "款式", requiredDate: "需要日期",
    candidatesTitle: "您的钻石候选", batchNote: "候选在批次有效期内为本订单专属保留。",
    select: "选择这颗", selected: "已选择", availability: { available: "可购", hold: "保留中", sold: "已售" },
    quoteTitle: "报价", metalAmount: "金属（预估重量）", packageAmount: "镶嵌·套餐", diamondAmount: "主石",
    total: "预估合计", deposit: "定金", balance: "尾款", validUntil: "有效期至", lead: (d) => `CAD 批准后制作 ~${d} 个工作日`,
    accept: "接受报价与条款", accepted: "已接受报价",
    cadTitle: "CAD 设计", cadVersion: (v) => `CAD V${v}`, cadApprove: "批准", cadRevise: "请求小幅修改",
    cadFeedbackPh: "修改 1、修改 2…（联系方式/链接自动屏蔽）", cadMeasure: "确认戒围 / 链长 / 尺寸",
    cadDecided: { approved: "已批准", minorRevision: "已请求小幅修改", styleChange: "款式变更" },
    progressTitle: "进度", actionsTitle: "等待您确认", logisticsTitle: "物流",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "色彩处理已公开",
  },
  supplierP: {
    title: "供应商门户", sub: (name) => `${name} — 仅显示分配的任务。绝不显示客户身份与销售价格。`,
    queue: "任务队列", taskTypes: { diamondCandidates: "钻石候选", weightLabor: "金重·工费", cad: "3D CAD", qc: "最终质检文件" },
    due: "截止", batchUntil: "批次有效期", required: "客户需要日期", styleRef: "款式",
    brief: "要求", status: { open: "待处理", submitted: "已提交", closed: "已关闭" }, openTask: "处理", empty: "暂无任务。",
    candTitle: "提交钻石候选", addRow: "添加候选", igiNo: "IGI 编号", costUsd: "成本 ($)",
    proportions: "台面/全深/冠部/亭部/长宽比/正面尺寸", media: "图片·视频", submit: "提交",
    wlTitle: "提交金重与工费", estWeight: "预估净金重 (g)", lossIncluded: "已含正常损耗",
    laborUsd: "工费 ($)", meleeUsd: "配钻/辅料 ($)", leadDays: "交期（天）", assumptions: "假设（尺寸·链长·主石尺寸）",
    cadTitle: "上传 CAD", cadFile: "CAD 文件/渲染图", qcTitle: "最终质检文件", qcVideo: "正/侧/背视频", qcCert: "证书", qcWeight: "实际重量证明 (g)",
  },
  opsA: {
    menu: { orders: "订单管控", styles: "款式库", benchmark: "钻石基准价", checklist: "每日检查" },
    orders: {
      title: "订单", owner: "负责人", required: "需要日期", nextAction: "待办", queryCode: "查询码",
      detail: "工作台", intake: "需求表", internalNotes: "内部备注（绝不向客户展示）",
      newPr: "创建采购任务", prType: "类型", supplier: "供应商", due: "截止日", batchUntil: "批次有效期", brief: "要求",
      candidates: "钻石候选", review: "内部审核", publish: "发布", unpublish: "取消发布",
      custPrice: "客户价 ($)", cost: "成本", reviews: { recommended: "推荐", alternate: "备选", excluded: "排除" },
      lock: "锁定到订单", locked: "已锁定",
      quoteTitle: "报价生成器", estWeight: "预估重量 (g)", metalRef: "金属基准 ($/g)", lossRate: "损耗率 (%)",
      nonMetal: "非金属套餐 ($)", internalCost: "内部：钻石成本 / 工费 / 杂费 / 风险 / 系数",
      createQuote: "创建报价", send: "发送给客户", markDeposit: "已收定金 → CAD",
      actualWeight: "实际重量 (g)", reconcile: "结算尾款",
      msTitle: "里程碑", publishClient: "对客户可见", cadTitle: "CAD 审核", sendCad: "发布 CAD 版本",
      auditTitle: "审计日志", actionsTitle: "客户任务", statusSet: "设置状态",
    },
    styles: {
      title: "款式库", available: "可售", published: "已发布", specs: "规格",
      newSpec: "新增规格", combo: "金属 + 尺寸 + 主石", variance: "允许偏差 %", materials: "辅料 ($)",
      addStyle: "新增款式", leadDays: "交期（天）", labor: "工费 ($)", estW: "预估重量 (g)",
    },
    bench: { title: "钻石基准价（9 形状 × 7 档）", note: "DEF VVS-VS · CVD · 后期处理 · IGI India — $/ct。仅更新单价与报价日期。", quoted: "报价日" },
    check: {
      title: "每日检查", waiting: "等待客户项", blocked: "受阻里程碑", expiring: "临近过期报价",
      lowCand: "已发布候选 <3 的选石订单", dueSoon: "临近需要日期的订单", openPr: "未响应采购任务", clear: "全部正常",
    },
  },
};

const es = {
  opsMetals: { "14ky": "Oro amarillo 14K", "18ky": "Oro amarillo 18K", "14kr": "Oro rosa 14K", "18kr": "Oro rosa 18K", "18kw": "Oro blanco 18K", pt: "Platino" },
  opsCategories: { ring: "Anillo", necklace: "Collar / Colgante", earrings: "Aretes", bangle: "Brazalete / Pulsera" },
  productLines: { solitaire: "Solitario / Piedra central grande", multi: "Multipiedra / Pavé" },
  orderStatus: {
    STYLE_SELECTION: "Selección de estilo", STONE_SELECTION: "Selección de piedra", QUOTATION: "Cotización",
    CAD: "Diseño CAD", PRODUCTION: "En producción", QC: "QC final", BALANCE: "Saldo pendiente",
    SHIPPING: "En envío", DELIVERED: "Entregado", ARCHIVED: "Archivado", PAUSED: "Pausado", CANCELLED: "Cancelado",
  },
  msStages: {
    depositReceived: "Depósito recibido", diamondLocked: "Diamante bloqueado", cadIssued: "CAD emitido",
    cadApproved: "CAD aprobado", productionStarted: "Producción iniciada", settingPolishing: "Engaste / Pulido",
    finalQcVideo: "Video QC final", igiInscriptionVerified: "IGI e inscripción verificados", actualMetalReconciled: "Metal real conciliado",
    balanceReceived: "Saldo recibido", sentDomesticWarehouse: "En almacén doméstico", oceanShipment: "Envío marítimo", deliveredArchived: "Entregado y archivado",
  },
  msStatus: { pending: "Pendiente", inProgress: "En curso", waitingClient: "Esperándote", blocked: "Bloqueado", done: "Hecho" },
  intake: {
    title: "Solicitud de Pedido a Medida", sub: "Cuéntanos qué quieres crear. Al enviar se emiten un Order ID y un código privado de seguimiento — sin pago hasta aceptar la cotización.",
    name: "Nombre", contact: "Correo o teléfono", productLine: "Línea de producto", category: "Categoría",
    style: "Estilo elegido (del catálogo)", noStyle: "Aún sin decidir", budget: "Presupuesto ($, opcional)", metal: "Metal",
    ringSize: "Talla de anillo (confirmación escrita requerida)", chainStyle: "Estilo de cadena", chainLength: "Largo de cadena",
    clasp: "Broche", wristSize: "Muñeca / diámetro interno", earringDetails: "Par a juego · poste o clip · izquierda/derecha",
    stoneTitle: "Preferencias de piedra central (solitario)",
    shape: "Forma", carat: "Quilates", color: "Color", clarity: "Pureza", growth: "Método de crecimiento", lab: "Laboratorio",
    colorTreatment: "Preferencia de tratamiento de color", fluorescence: "Fluorescencia", lwRatio: "Relación largo-ancho",
    multiTitle: "Especificación multipiedra",
    meleeSpec: "Especificación de melee (tamaño / cantidad)", overallDims: "Dimensiones generales",
    arrangement: "Disposición", multiStandard: "Estándar de color / pureza",
    bigStoneNote: "Sobre 2 ct normalmente recomendamos CVD con tratamiento de color divulgado — estable para uso diario y con mucha más disponibilidad.",
    requiredDate: "Fecha requerida", country: "País de entrega",
    terms: "Acepto los términos siguientes", submit: "Enviar solicitud",
    doneTitle: "Solicitud recibida", orderIdLbl: "Tu Order ID", codeLbl: "Código privado de seguimiento",
    doneNote: "Guarda este código — abre tu página de pedido sin cuenta. Te contactaremos en 1 día hábil.",
    goPortal: "Abrir mi pedido",
    termsBlocks: [
      "Se permiten revisiones menores del CAD tras el primer diseño.",
      "Cambiar de estilo o cancelar tras emitirse el CAD genera una tarifa de diseño.",
      "Cancelar tras iniciar producción descuenta una tarifa mínima más pérdidas no recuperables.",
      "La producción toma ~10 días hábiles tras aprobar el CAD (sin contar revisiones, feriados, flete y aduana).",
      "El peso del metal es estimado y se concilia con el peso final real.",
    ],
  },
  styleCat: {
    title: "Catálogo de Estilos", sub: "Estilos reproducibles confirmados con nuestro taller. Elige uno y empieza tu pedido.",
    start: "Empezar con este estilo", lead: (d) => `Producción ~${d} días hábiles`, weight: (g) => `Metal est. ${g}g`,
    awaitingMedia: "Material pendiente",
  },
  portal: {
    title: "Estado del Pedido", guestTitle: "Rastrea tu pedido", orderId: "Order ID", code: "Código",
    open: "Abrir", notFound: "Pedido no encontrado o código incorrecto.",
    statusLbl: "Estado actual", style: "Estilo", requiredDate: "Fecha requerida",
    candidatesTitle: "Tus diamantes candidatos", batchNote: "Los candidatos quedan reservados para este pedido hasta el vencimiento del lote.",
    select: "Elegir esta piedra", selected: "Seleccionado", availability: { available: "Disponible", hold: "Reservado", sold: "Vendido" },
    quoteTitle: "Cotización", metalAmount: "Metal (peso est.)", packageAmount: "Engaste y paquete", diamondAmount: "Piedra central",
    total: "Total estimado", deposit: "Depósito", balance: "Saldo", validUntil: "Válida hasta", lead: (d) => `Producción ~${d} días hábiles tras aprobar el CAD`,
    accept: "Aceptar cotización y términos", accepted: "Cotización aceptada",
    cadTitle: "Diseño CAD", cadVersion: (v) => `CAD V${v}`, cadApprove: "Aprobar", cadRevise: "Pedir revisión menor",
    cadFeedbackPh: "Cambio 1, cambio 2… (contactos/enlaces bloqueados)", cadMeasure: "Confirmar talla / largo de cadena / dimensiones",
    cadDecided: { approved: "Aprobado", minorRevision: "Revisión menor solicitada", styleChange: "Cambio de estilo" },
    progressTitle: "Progreso", actionsTitle: "Esperándote", logisticsTitle: "Logística",
    igi: "IGI", growth: { CVD: "CVD", HPHT: "HPHT" }, treated: "Tratamiento de color divulgado",
  },
  supplierP: {
    title: "Portal del Proveedor", sub: (name) => `${name} — solo tareas asignadas. Nunca se muestran identidad del cliente ni precios de venta.`,
    queue: "Cola de tareas", taskTypes: { diamondCandidates: "Candidatos de diamante", weightLabor: "Peso de metal y mano de obra", cad: "CAD 3D", qc: "Archivos de QC final" },
    due: "Vence", batchUntil: "Lote válido hasta", required: "Fecha requerida del cliente", styleRef: "Estilo",
    brief: "Requisitos", status: { open: "Abierta", submitted: "Enviada", closed: "Cerrada" }, openTask: "Abrir", empty: "Sin tareas.",
    candTitle: "Enviar candidatos", addRow: "Añadir candidato", igiNo: "N.º IGI", costUsd: "Costo ($)",
    proportions: "Mesa/Prof./Corona/Pabellón/L-A/Cara", media: "Imagen y video", submit: "Enviar",
    wlTitle: "Enviar peso y mano de obra", estWeight: "Peso neto est. (g)", lossIncluded: "Incluye merma normal",
    laborUsd: "Mano de obra ($)", meleeUsd: "Melee / materiales ($)", leadDays: "Plazo (días)", assumptions: "Supuestos (talla, cadena, dimensiones)",
    cadTitle: "Subir CAD", cadFile: "Archivo CAD / render", qcTitle: "Archivos QC final", qcVideo: "Video frontal/lateral/trasero", qcCert: "Certificado", qcWeight: "Evidencia de peso real (g)",
  },
  opsA: {
    menu: { orders: "Control de Pedidos", styles: "Biblioteca de Estilos", benchmark: "Precios de Diamante", checklist: "Checklist Diario" },
    orders: {
      title: "Pedidos", owner: "Responsable", required: "Requerido", nextAction: "Acciones abiertas", queryCode: "Código",
      detail: "Mesa de trabajo", intake: "Solicitud", internalNotes: "Notas internas (nunca visibles al cliente)",
      newPr: "Crear solicitud de compra", prType: "Tipo", supplier: "Proveedor", due: "Vence", batchUntil: "Lote válido hasta", brief: "Requisitos",
      candidates: "Candidatos", review: "Revisión interna", publish: "Publicar", unpublish: "Despublicar",
      custPrice: "Precio cliente ($)", cost: "Costo", reviews: { recommended: "Recomendado", alternate: "Alternativo", excluded: "Excluido" },
      lock: "Bloquear para el pedido", locked: "Bloqueado",
      quoteTitle: "Generador de cotización", estWeight: "Peso est. (g)", metalRef: "Ref. metal ($/g)", lossRate: "Merma (%)",
      nonMetal: "Paquete no metálico ($)", internalCost: "Interno: costo diamante / mano de obra / extras / riesgo / multiplicador",
      createQuote: "Crear cotización", send: "Enviar al cliente", markDeposit: "Depósito recibido → CAD",
      actualWeight: "Peso real (g)", reconcile: "Conciliar saldo",
      msTitle: "Hitos", publishClient: "Visible al cliente", cadTitle: "Revisiones CAD", sendCad: "Emitir versión CAD",
      auditTitle: "Registro de auditoría", actionsTitle: "Acciones del cliente", statusSet: "Cambiar estado",
    },
    styles: {
      title: "Biblioteca de Estilos", available: "A la venta", published: "Publicado", specs: "Especificaciones",
      newSpec: "Añadir especificación", combo: "Metal + talla + piedra central", variance: "Variación %", materials: "Materiales ($)",
      addStyle: "Añadir estilo", leadDays: "Plazo (días)", labor: "Mano de obra ($)", estW: "Peso est. (g)",
    },
    bench: { title: "Benchmark de Diamantes (9 formas × 7 rangos)", note: "DEF VVS-VS · CVD · tratamiento posterior · IGI India — $/ct. Actualiza solo precio y fecha.", quoted: "Cotizado" },
    check: {
      title: "Checklist Diario", waiting: "Esperando al cliente", blocked: "Hitos bloqueados", expiring: "Cotizaciones por vencer",
      lowCand: "Pedidos en selección con <3 candidatos publicados", dueSoon: "Pedidos cerca de la fecha requerida", openPr: "Solicitudes de compra abiertas", clear: "Todo en orden",
    },
  },
};

export const opsStrings = { en, ko, zh, es };
