// 신규 플랫폼 화면(검색/위저드/마이페이지/벤더/어드민/가이드) 전체 문자열 — 4개 언어 완전 지원.
// 데이터는 키(shape/metal/stage/status)로 저장되고 여기서 언어별 라벨로 매핑된다.

const en = {
  nav: { diamonds: "Diamonds", designs: "Designs", gallery: "Design Gallery", process: "Process", custom: "Custom Order", startCustom: "Start Custom", guide: "Guide", login: "Sign in", logout: "Sign out", account: "My Page", vendorPortal: "Vendor Portal", admin: "Admin" },
  common: {
    next: "Next", prev: "Back", submit: "Submit", cancel: "Cancel", add: "Add", all: "All",
    view: "View", delete: "Delete", new: "New", none: "—", notFound: "Page not found.", date: "Date", status: "Status",
  },
  shapes: { round: "Round", oval: "Oval", princess: "Princess", emerald: "Emerald", pear: "Pear", marquise: "Marquise", cushion: "Cushion", radiant: "Radiant", asscher: "Asscher", heart: "Heart" },
  metals: { wg18: "18K White Gold", yg18: "18K Yellow Gold", rg18: "18K Rose Gold", pt950: "Platinum PT950" },
  categories: { ring: "Rings", necklace: "Necklaces", earring: "Earrings", bracelet: "Bracelets" },
  status: {
    DRAFT: "Draft", SUBMITTED: "Submitted", VENDOR_ASSIGNED: "Atelier assigned",
    PROPOSAL_UPLOADED: "Proposal ready", REVISION_REQUESTED: "Revision requested", CONFIRMED: "Confirmed",
    DEPOSIT_PAID: "Deposit paid", IN_PRODUCTION: "In production", QUALITY_CHECK: "Quality check",
    FINAL_PAYMENT_PAID: "Final payment paid", SHIPPED: "Shipped", DELIVERED: "Delivered",
    COMPLETED: "Completed", CANCELLED: "Cancelled", ON_HOLD: "On hold",
  },
  stages: { production: "In production", qc: "Quality check", ready: "Preparing shipment", shipping: "In transit", delivered: "Delivered" },
  login: {
    title: "Sign in", signupTitle: "Create account", name: "Name", email: "Email", password: "Password",
    loginBtn: "Sign in", signupBtn: "Create account",
    toSignup: "New here? Create an account", toLogin: "Already have an account? Sign in",
    demoTitle: "Demo accounts (password: demo1234)",
    staffTitle: "Staff sign-in", staffSub: "Admin back office for BeloveD operations.",
    vendorTitle: "Workshop sign-in", vendorSub: "Enter the access code we sent you — no password needed.",
    codeLabel: "Access code", codeBtn: "Enter",
    staffLink: "Staff sign-in", vendorLink: "Workshop sign-in", customerLink: "Customer sign-in",
    dealerApplyHint: "Want to partner as a dealer?", dealerApplyLink: "Apply here",
    errors: { rateLimited: "Too many attempts — try again in a minute.", badCredentials: "Invalid email or password. (Demo password: demo1234)", emailExists: "This email is already registered.", wrongPortal: "This account uses a different sign-in.", badCode: "Invalid or inactive access code.", accountSuspended: "This account is suspended." },
  },
  diamonds: {
    title: "Diamonds", sub: "IGI·GIA certified lab-grown diamonds — each one passes through our hands before it reaches yours.",
    caratMin: "Carat min", caratMax: "Carat max", maxPrice: "Max price ($)",
    cut: "Cut", color: "Color", clarity: "Clarity", cert: "Certificate", sort: "Sort",
    sortPriceAsc: "Price: low to high", sortPriceDesc: "Price: high to low", sortCaratDesc: "Carat: high to low",
    byShape: "Shop by Shape", reset: "Reset filters", count: (n) => `${n} stones`, empty: "No diamonds match these filters.",
  },
  detail: {
    notFound: "Diamond not found.", shape: "Shape", carat: "Carat", cut: "Cut", color: "Color",
    clarity: "Clarity", certOrg: "Certified by", certNo: "Certificate no.",
    certNote: (org, no) => `The original certificate ships with the piece. (${org} ${no})`,
    orderCta: "Custom order with this diamond", back: "Back to list",
  },
  templates: {
    title: "Design Gallery", sub: "Signature designs from the BeloveD atelier. Choose one — we make it yours alone.",
    fromPrice: (p) => `Setting from ${p}`, quote: "Quote on request",
  },
  wizard: {
    title: "Custom Order", sub: "Choose a design and a stone — the atelier presents proposals in photographs and film first. Nothing to pay until you confirm.",
    steps: ["① Design", "② Diamond", "③ Details", "④ Review"],
    skipHint: "Not sure yet? Skip this step — we'll propose stones that fit your budget.",
    nextNoStone: "Continue without a stone",
    metal: "Metal", size: "Size (ring size / length)", sizePh: "e.g. US 6 / 42cm", engraving: "Engraving (optional)",
    budget: "Budget ($, optional)", notes: "Requests",
    notesPh: "Describe the details you want. (Contact info and links are blocked automatically)",
    summary: "Order summary", design: "Design", diamond: "Diamond", recommend: "Atelier recommendation requested",
    metalSize: "Metal / Size", expected: "Estimated from", quoteLater: "Quote provided with the proposal",
    submitNote: "After you submit, our atelier uploads proposals here. Production starts only after you confirm and pay the deposit (30%).",
    submit: "Submit order", loginToSubmit: "Sign in to submit",
  },
  account: {
    title: "My Page", welcome: (name) => `Welcome, ${name}.`,
    tabs: { orders: "Custom Orders", payments: "Payments", profile: "Profile" },
    emptyOrders: "No orders yet. Start in the", gallery: "Design Gallery",
    orderNo: "Order", design: "Design", emptyPayments: "No payments yet.",
    when: "Date", type: "Type", amount: "Amount", state: "Status", paid: "Paid",
    deposit: "Deposit", final: "Final payment",
    nameLbl: "Name", emailLbl: "Email", roleLbl: "Role", customerRole: "Customer",
    profileHint: "Shipping address and contact are collected at checkout (never shared with the atelier).",
  },
  request: {
    notFound: "Order not found.",
    depositTitle: "Deposit payment", totalAmount: "Total production cost",
    depositLbl: (pct) => `Deposit (${pct}%)`, payDeposit: (amt) => `Pay ${amt} (mock payment)`,
    mockNote: "In production this opens Stripe checkout.",
    finalTitle: "Final payment", qcHint: "Quality check in progress. Shipping starts after the final payment.",
    payFinal: (amt) => `Pay final ${amt} (mock payment)`,
    stagesTitle: "Production & shipping", tracking: "Tracking no.", confirmReceipt: "Confirm receipt",
    productionTitle: "Production log", proposalsTitle: "Proposals",
    preparing: "Our atelier is preparing your proposal. You'll review and confirm it here.",
    proposalV: (v) => `Proposal v${v}`,
    confirmChip: "Confirm this proposal", reviseChip: "Request revision",
    choices: { size: "Adjust size", stone: "Move stone", band: "Band thickness", color: "Color tone", engraving: "Engraving position" },
    detailReq: "Details (contact info and links are blocked)",
    confirmBtn: "Confirm proposal", reviseBtn: "Send revision request",
    confirmedNote: "✓ Confirmed", revisionNote: (c) => `Revision requested: ${c}`,
    cancelOrder: "Cancel order", cancelAsk: "Cancel this order?",
  },
  vendor: {
    title: "Vendor Portal", sub: (name) => `${name} — only your assigned orders are shown. Customers stay anonymous.`,
    tabs: { new: "Awaiting response", waiting: "Customer reviewing", production: "Production & QC", done: "Done" },
    empty: "No orders in this state.", order: "Order", design: "Design", elapsed: "Elapsed",
    hours: (h) => `${h}h`, slaWarn: " SLA exceeded", work: "Open",
    notAssigned: "This order is not assigned to you.",
    specTitle: "Order specification", diamondRow: "Diamond", recommend: "Stone recommendation requested",
    metalRow: "Metal", sizeRow: "Size", engravingRow: "Engraving", budgetRow: "Budget", notesRow: "Requests",
    uploadTitle: (v) => `Upload proposal (v${v})`, comment: "Comment (contact info and links are blocked)",
    uploadBtn: "Upload proposal",
    startTitle: "Start production", startHint: "Deposit received. Starting production shows progress to the customer.",
    startBtn: "Start production",
    progressTitle: "Production progress", progressUpload: "Upload progress photos", qcRequest: "Done → request QC",
    prodLog: "Production log", myProposals: "Uploaded proposals", noProposals: "No proposals yet. Upload the first one.",
    fb: "Customer feedback", fbConfirmed: "✓ Confirmed", fbRevise: (c) => `Revision: ${c}`,
  },
  picker: {
    hint: (n) => `${n} selected`,
    dropHint: "Drag photos or videos here", dropSub: "or tap to choose from your phone",
    sampleToggle: "Or pick a sample",
    limitHint: (n, max) => `${n}/${max} attached · tap to choose from your phone`,
    maxError: (max) => `You can attach up to ${max} photos or videos.`,
    attachedLabel: "Attached files", photoLabel: "Photo", videoLabel: "Video", removeLabel: "Remove",
    fileLabel: "Upload file", fileError: (mb) => `File too large — keep it under ${mb}MB.`, typeError: "Only photos and videos are supported.",
    optimizing: "Optimizing media...",
    optimizedLabel: "Optimized",
    optimizedNotice: (n) => `${n} image${n > 1 ? "s" : ""} compressed for upload.`,
    videoNotice: "Video attached as an optimized preview file.",
    optimizeError: "We could not optimize that file. Try a different photo or video.",
    labels: { sol: "Solitaire", band: "Band", pendant: "Pendant", studs: "Studs", bracelet: "Bracelet", loose: "Loose stone", video: "Stone video" },
  },
  admin: {
    title: "Admin",
    menu: { dashboard: "Dashboard", diamonds: "Diamonds", pool: "Diamond Pool", templates: "Templates", orders: "Orders", vendors: "Suppliers", settings: "Settings" },
    dash: {
      active: "Active orders", unassigned: "Unassigned", sla: "SLA 48h+ overdue", inventory: "Stones in inventory",
      slaWarn: (codes) => `Vendor unresponsive over 48h: ${codes} — reassign in Orders.`,
      depositWait: (codes) => `Awaiting deposit: ${codes}`, noOrders: "No paid orders yet.",
    },
    pool: {
      title: "Vendor Diamond Pool", sub: "All suppliers' standing stock. Add stones, manage photos, and archive any entry.",
      filterAll: "All suppliers", supplier: "Supplier", stone: "Stone", fourC: "4C", cert: "Certificate",
      cost: "Cost", statusCol: "Status", photos: "Photos", edit: "Photos", save: "Save",
      archive: "Archive", restore: "Restore", archived: "Archived",
      avail: { available: "Available", unavailable: "Off", sold: "Sold" },
      newTitle: "Add a stone", addBtn: "Add to pool", count: (n) => `${n} stones`,
    },
    dia: {
      bulkTitle: "Bulk price adjustment", bulkBtn: (p) => `Adjust all by ${p}%`,
      bulkHint: "Positive = increase, negative = decrease. Rounded to $10.",
      invTitle: "Inventory", stone: "Stone", fourC: "4C", cert: "Certificate",
      priceCol: "Price ($, edit inline)", visibleCol: "Visible", pub: "Public", priv: "Hidden",
      newTitle: "Add diamond (manual media upload)", shape: "Shape", carat: "Carat", cut: "Cut",
      color: "Color", clarity: "Clarity", certOrg: "Cert. body", certNo: "Cert. no.", price: "Price ($)", addBtn: "Add",
    },
    tpl: {
      title: "Templates", name: "Name", category: "Category", basePrice: "Base price", visibleCol: "Visible",
      pub: "Public", priv: "Hidden", newTitle: "Add template (sample design)", desc: "Description", addBtn: "Add",
      nameHint: "Entered text is used for all languages — localize later if needed.",
    },
    orders: {
      title: "All orders", order: "Order", customer: "Customer (PII — admin only)", design: "Design",
      vendorCol: "Vendor", payment: "Payment", force: "Force transition", assign: "Assign…", transit: "Transition…",
      trackingPh: "Enter tracking no.", dep: "Deposit", fin: "Final",
    },
    vendors: {
      title: "Supplier accounts", displayName: "Display name", emailCol: "Email", assigned: "Assigned",
      uploads: "Proposals", stateCol: "State", active: "Active", suspended: "Suspended",
      codeCol: "Access code", copyLink: "Copy link",
      issueTitle: "Issue supplier account", issueHint: "An access code is generated automatically — share the code or magic link with the workshop. No password.",
      nameLbl: "Display name (e.g. ATELIER-03)", emailLbl: "Email",
      issueBtn: "Issue access code", issuedTitle: (n) => `${n} — send this to the workshop`,
    },
    settings: {
      payTitle: "Payment settings", depositPct: "Deposit rate (%)", applyNote: "Applies to newly confirmed orders.",
      stagesTitle: "Shipping stage labels", heroTitle: "Hero video slot",
      heroNote: "Current: /assets/diamond-noir-white.mp4 — replace the file to swap in real footage instantly.",
      demoTitle: "Demo data", resetBtn: "Reset to seed data", resetAsk: "Reset all demo data?",
    },
  },
  guide: {
    hub: {
      kicker: "Diamond guide",
      title: "Choose with confidence.",
      sub: "Quiet, practical notes on lab-grown quality, choosing your stone, and the decisions behind a commission.",
      cards: {
        lab: { kicker: "Lab-grown", title: "Same fire. Smarter origin.", body: "How lab-grown diamonds compare and what disclosures matter." },
        fourc: { kicker: "4C", title: "Cut, color, clarity, carat.", body: "The practical way to prioritize visible brilliance." },
        custom: { kicker: "Custom", title: "From brief to final QC.", body: "What happens after you start a custom order." },
      },
    },
    lab: {
      title: "What is a lab-grown diamond?",
      p1: "A lab-grown diamond is a real diamond — physically, chemically and optically identical to a mined one. The only difference is where it was born: a laboratory instead of the ground.",
      h1: "Identical to mined", p2: "Same hardness (Mohs 10), refractive index and dispersion. Even gemologists cannot tell them apart without specialized equipment.",
      h2: "IGI · GIA certified", p3: "Every BeloveD stone ships with an IGI or GIA certificate you can verify by its number.",
      h3: "Honest pricing", p4: "Without mining and distribution premiums, you get a bigger, cleaner stone for the same budget — at about half the price.",
      cta: "Browse diamonds", next: "Next: The 4C guide →",
    },
    fourc: {
      title: "The 4C Guide",
      caratH: "Carat", caratP: "The stone's weight (1ct = 0.2g). The same carat can look larger or smaller depending on the cut.",
      cutH: "Cut", cutP: "The most important factor for brilliance. An Excellent cut returns the maximum light.",
      colorH: "Color", colorP: "From D (colorless) to Z. D–F are colorless; G–H are near-colorless with differences invisible to the eye.",
      clarityH: "Clarity", clarityP: "The degree of inclusions. From IF (flawless) down to VS2, inclusions are invisible to the naked eye.",
      tip: "Tip: the most efficient combination is an Excellent cut + F–G color + VS1–VS2 clarity.",
      cta: "Start a custom order with this in mind",
    },
  },
};

const ko = {
  nav: { diamonds: "다이아몬드", designs: "디자인", gallery: "디자인 갤러리", process: "과정", custom: "주문제작", startCustom: "주문제작 시작", guide: "가이드", login: "로그인", logout: "로그아웃", account: "마이페이지", vendorPortal: "벤더 포털", admin: "어드민" },
  common: {
    next: "다음", prev: "이전", submit: "제출", cancel: "취소", add: "등록", all: "전체",
    view: "상세 보기", delete: "삭제", new: "새로 만들기", none: "—", notFound: "페이지를 찾을 수 없습니다.", date: "날짜", status: "상태",
  },
  shapes: { round: "라운드", oval: "오벌", princess: "프린세스", emerald: "에메랄드", pear: "페어", marquise: "마퀴즈", cushion: "쿠션", radiant: "래디언트", asscher: "아셔", heart: "하트" },
  metals: { wg18: "18K 화이트골드", yg18: "18K 옐로골드", rg18: "18K 로즈골드", pt950: "플래티넘 PT950" },
  categories: { ring: "링", necklace: "네크리스", earring: "이어링", bracelet: "브레이슬릿" },
  status: {
    DRAFT: "작성중", SUBMITTED: "접수됨", VENDOR_ASSIGNED: "제작팀 배정",
    PROPOSAL_UPLOADED: "시안 도착", REVISION_REQUESTED: "수정 요청됨", CONFIRMED: "시안 확정",
    DEPOSIT_PAID: "디파짓 결제완료", IN_PRODUCTION: "제작중", QUALITY_CHECK: "검수중",
    FINAL_PAYMENT_PAID: "잔금 결제완료", SHIPPED: "배송중", DELIVERED: "배송완료",
    COMPLETED: "완료", CANCELLED: "취소됨", ON_HOLD: "보류",
  },
  stages: { production: "제작중", qc: "검수", ready: "배송준비", shipping: "배송중", delivered: "배송완료" },
  login: {
    title: "로그인", signupTitle: "회원가입", name: "이름", email: "이메일", password: "비밀번호",
    loginBtn: "로그인", signupBtn: "가입하기",
    toSignup: "처음이신가요? 회원가입", toLogin: "이미 계정이 있으신가요? 로그인",
    demoTitle: "데모 계정 (비밀번호 demo1234)",
    staffTitle: "스태프 로그인", staffSub: "BeloveD 운영 어드민 전용 백오피스입니다.",
    vendorTitle: "공방 로그인", vendorSub: "전달받은 접근 코드를 입력하세요 — 비밀번호가 필요 없습니다.",
    codeLabel: "접근 코드", codeBtn: "입장",
    staffLink: "스태프 로그인", vendorLink: "공방 로그인", customerLink: "고객 로그인",
    dealerApplyHint: "딜러로 함께하고 싶으세요?", dealerApplyLink: "신청하기",
    errors: { rateLimited: "시도가 너무 많습니다 — 1분 후 다시 시도해주세요.", badCredentials: "이메일 또는 비밀번호가 올바르지 않습니다. (데모 비밀번호: demo1234)", emailExists: "이미 가입된 이메일입니다.", wrongPortal: "이 계정은 다른 로그인 경로를 사용합니다.", badCode: "유효하지 않거나 비활성된 접근 코드입니다.", accountSuspended: "정지된 계정입니다." },
  },
  diamonds: {
    title: "다이아몬드", sub: "모든 스톤은 IGI·GIA 인증 랩그로운 다이아몬드. 저희 손으로 직접 검수한 모습 그대로 보여드립니다.",
    caratMin: "캐럿 min", caratMax: "캐럿 max", maxPrice: "최대 가격($)",
    cut: "컷", color: "컬러", clarity: "클래리티", cert: "인증", sort: "정렬",
    sortPriceAsc: "가격 낮은순", sortPriceDesc: "가격 높은순", sortCaratDesc: "캐럿 높은순",
    byShape: "쉐입으로 찾기", reset: "필터 초기화", count: (n) => `${n}개 스톤`, empty: "조건에 맞는 다이아몬드가 없습니다.",
  },
  detail: {
    notFound: "해당 다이아몬드를 찾을 수 없습니다.", shape: "쉐입", carat: "캐럿", cut: "컷", color: "컬러",
    clarity: "클래리티", certOrg: "인증기관", certNo: "인증번호",
    certNote: (org, no) => `인증서 원본은 실물과 함께 제공됩니다. (${org} ${no})`,
    orderCta: "이 다이아몬드로 주문제작", back: "목록으로",
  },
  templates: {
    title: "디자인 갤러리", sub: "BeloveD 아틀리에의 시그니처 디자인. 마음에 닿는 하나를 고르시면, 오직 당신의 것으로 완성합니다.",
    fromPrice: (p) => `세팅 ${p}~`, quote: "견적 문의",
  },
  wizard: {
    title: "주문제작", sub: "디자인과 스톤을 고르시면, 아틀리에가 사진과 영상 시안으로 먼저 보여드립니다. 확정 전에는 결제를 청하지 않습니다.",
    steps: ["① 디자인", "② 다이아몬드", "③ 세부사항", "④ 검토·제출"],
    skipHint: "스톤을 아직 못 정하셨다면 건너뛰어도 됩니다 — 예산에 맞는 스톤을 시안과 함께 제안해드립니다.",
    nextNoStone: "스톤 없이 다음",
    metal: "메탈", size: "사이즈 (호수/길이)", sizePh: "예: 11호 / 42cm", engraving: "각인 (선택)",
    budget: "예산 ($, 선택)", notes: "요청사항",
    notesPh: "원하는 디테일을 적어주세요. (연락처·외부 링크는 자동 차단됩니다)",
    summary: "주문 요약", design: "디자인", diamond: "다이아몬드", recommend: "제작팀 추천 요청",
    metalSize: "메탈/사이즈", expected: "예상 시작가", quoteLater: "시안과 함께 견적 제공",
    submitNote: "제출 후 제작팀이 시안을 올리면 여기서 확인할 수 있습니다. 시안 컨펌 시 디파짓(30%) 결제로 제작이 시작됩니다.",
    submit: "주문 제출", loginToSubmit: "로그인 후 제출",
  },
  account: {
    title: "마이페이지", welcome: (name) => `${name}님, 환영합니다.`,
    tabs: { orders: "주문제작 현황", payments: "결제 내역", profile: "프로필" },
    emptyOrders: "아직 주문이 없습니다. 여기서 시작해보세요:", gallery: "디자인 갤러리",
    orderNo: "주문번호", design: "디자인", emptyPayments: "결제 내역이 없습니다.",
    when: "일시", type: "구분", amount: "금액", state: "상태", paid: "결제 완료",
    deposit: "디파짓", final: "잔금",
    nameLbl: "이름", emailLbl: "이메일", roleLbl: "역할", customerRole: "고객",
    profileHint: "배송지·연락처는 결제 단계에서 입력받습니다 (제작팀에는 공유되지 않습니다).",
  },
  request: {
    notFound: "주문을 찾을 수 없습니다.",
    depositTitle: "디파짓 결제", totalAmount: "총 제작금액",
    depositLbl: (pct) => `디파짓 (${pct}%)`, payDeposit: (amt) => `${amt} 결제하기 (모의 결제)`,
    mockNote: "실서비스에서는 Stripe 결제창으로 연결됩니다.",
    finalTitle: "잔금 결제", qcHint: "검수가 진행 중입니다. 잔금 결제 후 배송이 시작됩니다.",
    payFinal: (amt) => `잔금 ${amt} 결제하기 (모의 결제)`,
    stagesTitle: "제작·배송 단계", tracking: "운송장", confirmReceipt: "수령 확인",
    productionTitle: "제작 과정", proposalsTitle: "시안",
    preparing: "제작팀이 시안을 준비하고 있습니다. 시안이 올라오면 여기에서 확인·컨펌할 수 있습니다.",
    proposalV: (v) => `시안 v${v}`,
    confirmChip: "이 시안으로 확정", reviseChip: "수정 요청",
    choices: { size: "사이즈 조정", stone: "스톤 위치 변경", band: "밴드 두께", color: "컬러 톤", engraving: "각인 위치" },
    detailReq: "상세 요청 (연락처·링크 자동 차단)",
    confirmBtn: "시안 확정하기", reviseBtn: "수정 요청 보내기",
    confirmedNote: "✓ 확정함", revisionNote: (c) => `수정 요청: ${c}`,
    cancelOrder: "주문 취소", cancelAsk: "주문을 취소할까요?",
  },
  vendor: {
    title: "벤더 포털", sub: (name) => `${name} — 배정된 주문만 표시됩니다. 고객 정보는 익명 처리됩니다.`,
    tabs: { new: "응답 대기", waiting: "고객 검토중", production: "제작·검수", done: "완료" },
    empty: "해당 상태의 주문이 없습니다.", order: "주문", design: "디자인", elapsed: "경과",
    hours: (h) => `${h}시간`, slaWarn: " SLA 초과", work: "작업하기",
    notAssigned: "배정된 주문이 아닙니다.",
    specTitle: "주문 사양", diamondRow: "다이아몬드", recommend: "스톤 추천 요청",
    metalRow: "메탈", sizeRow: "사이즈", engravingRow: "각인", budgetRow: "예산", notesRow: "요청사항",
    uploadTitle: (v) => `시안 업로드 (v${v})`, comment: "코멘트 (연락처·링크 자동 차단)",
    uploadBtn: "시안 올리기",
    startTitle: "제작 시작", startHint: "디파짓이 결제되었습니다. 제작을 시작하면 고객에게 단계가 표시됩니다.",
    startBtn: "제작 시작",
    progressTitle: "제작 진행", progressUpload: "진행 사진 올리기", qcRequest: "제작 완료 → 검수 요청",
    prodLog: "제작 과정 기록", myProposals: "업로드한 시안", noProposals: "아직 시안이 없습니다. 첫 시안을 올려주세요.",
    fb: "고객 피드백", fbConfirmed: "✓ 확정", fbRevise: (c) => `수정 요청: ${c}`,
  },
  picker: {
    hint: (n) => `${n}개 선택됨`,
    dropHint: "사진·영상을 여기로 끌어다 놓으세요", dropSub: "또는 눌러서 휴대폰에서 선택",
    sampleToggle: "또는 샘플에서 선택",
    limitHint: (n, max) => `${n}/${max}개 첨부됨 · 눌러서 휴대폰에서 선택`,
    maxError: (max) => `사진 또는 영상은 최대 ${max}개까지 첨부할 수 있습니다.`,
    attachedLabel: "첨부 파일", photoLabel: "사진", videoLabel: "영상", removeLabel: "삭제",
    fileLabel: "파일 업로드", fileError: (mb) => `파일이 너무 큽니다 — ${mb}MB 이하로 올려주세요.`, typeError: "사진과 영상만 올릴 수 있습니다.",
    optimizing: "미디어 최적화 중...",
    optimizedLabel: "최적화됨",
    optimizedNotice: (n) => `이미지 ${n}개를 업로드용으로 압축했습니다.`,
    videoNotice: "영상은 앱이 느려지지 않도록 가벼운 미리보기 파일로 첨부했습니다.",
    optimizeError: "파일을 최적화하지 못했습니다. 다른 사진이나 영상을 올려주세요.",
    labels: { sol: "솔리테어", band: "밴드", pendant: "펜던트", studs: "스터드", bracelet: "브레이슬릿", loose: "루스 스톤", video: "스톤 영상" },
  },
  admin: {
    title: "어드민",
    menu: { dashboard: "대시보드", diamonds: "다이아몬드", pool: "다이아 풀", templates: "템플릿", orders: "주문 감독", vendors: "서플라이어", settings: "설정" },
    dash: {
      active: "진행중 주문", unassigned: "벤더 미배정", sla: "SLA 48h 초과", inventory: "인벤토리 스톤",
      slaWarn: (codes) => `벤더 무응답 48시간 초과: ${codes} — 주문 감독에서 재배정하세요.`,
      depositWait: (codes) => `디파짓 대기: ${codes}`, noOrders: "아직 결제된 주문이 없습니다.",
    },
    pool: {
      title: "벤더 다이아 풀", sub: "모든 벤더의 상설 재고. 스톤 추가·사진 관리·아카이브 가능.",
      filterAll: "전체 벤더", supplier: "벤더", stone: "스톤", fourC: "4C", cert: "인증",
      cost: "원가", statusCol: "상태", photos: "사진", edit: "사진", save: "저장",
      archive: "아카이브", restore: "복원", archived: "아카이브됨",
      avail: { available: "재고 있음", unavailable: "내림", sold: "판매됨" },
      newTitle: "스톤 추가", addBtn: "풀에 추가", count: (n) => `스톤 ${n}개`,
    },
    dia: {
      bulkTitle: "일괄 가격 조정", bulkBtn: (p) => `전체 ${p}% 조정`,
      bulkHint: "양수 = 인상, 음수 = 인하. $10 단위 반올림.",
      invTitle: "인벤토리", stone: "스톤", fourC: "4C", cert: "인증",
      priceCol: "가격 ($, 직접 수정)", visibleCol: "공개", pub: "공개", priv: "비공개",
      newTitle: "새 다이아몬드 등록 (미디어 수동 업로드)", shape: "쉐입", carat: "캐럿", cut: "컷",
      color: "컬러", clarity: "클래리티", certOrg: "인증기관", certNo: "인증번호", price: "가격 ($)", addBtn: "등록",
    },
    tpl: {
      title: "템플릿", name: "이름", category: "카테고리", basePrice: "세팅가", visibleCol: "공개",
      pub: "공개", priv: "비공개", newTitle: "새 템플릿 (샘플 디자인) 등록", desc: "설명", addBtn: "등록",
      nameHint: "입력한 텍스트는 모든 언어에 공통 적용됩니다 — 추후 언어별 현지화 가능.",
    },
    orders: {
      title: "전체 주문", order: "주문", customer: "고객 (PII — 어드민만)", design: "디자인",
      vendorCol: "벤더", payment: "결제", force: "강제 전이", assign: "배정…", transit: "전이…",
      trackingPh: "운송장 입력", dep: "디파짓", fin: "잔금",
    },
    vendors: {
      title: "서플라이어 계정", displayName: "표시명", emailCol: "이메일", assigned: "배정 주문",
      uploads: "업로드 시안", stateCol: "상태", active: "활성", suspended: "정지",
      codeCol: "접근 코드", copyLink: "링크 복사",
      issueTitle: "서플라이어 계정 발급", issueHint: "접근 코드가 자동 생성됩니다 — 코드나 매직링크를 공방에 전달하세요. 비밀번호 없음.",
      nameLbl: "표시명 (예: ATELIER-03)", emailLbl: "이메일",
      issueBtn: "접근 코드 발급", issuedTitle: (n) => `${n} — 공방에 이걸 전달하세요`,
    },
    settings: {
      payTitle: "결제 설정", depositPct: "디파짓 비율 (%)", applyNote: "새 주문 컨펌 시점부터 적용됩니다.",
      stagesTitle: "배송 단계 라벨", heroTitle: "히어로 영상 슬롯",
      heroNote: "현재: /assets/diamond-noir-white.mp4 — 실사 촬영본 확보 시 같은 파일명으로 교체하면 즉시 반영됩니다.",
      demoTitle: "데모 데이터", resetBtn: "시드 데이터로 초기화", resetAsk: "모든 데모 데이터를 초기화할까요?",
    },
  },
  guide: {
    hub: {
      kicker: "다이아몬드 가이드",
      title: "망설임 없이 고를 수 있도록.",
      sub: "랩그로운 품질과 스톤 취향, 주문제작의 순간마다 필요한 이야기를 간결하게 담았습니다.",
      cards: {
        lab: { kicker: "랩그로운", title: "같은 광채, 더 합리적인 시작.", body: "랩그로운 다이아몬드의 차이와 꼭 확인해야 할 정보를 정리했습니다." },
        fourc: { kicker: "4C", title: "컷, 컬러, 클래리티, 캐럿.", body: "눈에 보이는 아름다움을 기준으로 우선순위를 잡는 방법입니다." },
        custom: { kicker: "주문제작", title: "상담부터 최종 QC까지.", body: "주문제작을 시작한 뒤 어떤 과정으로 진행되는지 안내합니다." },
      },
    },
    lab: {
      title: "랩그로운 다이아몬드란?",
      p1: "랩그로운 다이아몬드는 천연 다이아몬드와 물리적·화학적·광학적으로 100% 동일한 진짜 다이아몬드입니다. 유일한 차이는 탄생지 — 땅속 대신 실험실에서 성장합니다.",
      h1: "천연과 동일한 물성", p2: "경도(모스 10), 굴절률, 분산도 모두 동일합니다. 보석 감정사도 전용 장비 없이는 구분할 수 없습니다.",
      h2: "IGI·GIA 인증", p3: "BeloveD의 모든 스톤은 IGI 또는 GIA 인증서가 함께 제공되며, 인증번호로 진위를 직접 조회할 수 있습니다.",
      h3: "정직한 가격", p4: "채굴·유통 프리미엄이 없어 동급 천연 대비 절반 수준의 가격으로, 같은 예산에 더 크고 더 깨끗한 스톤을 선택할 수 있습니다.",
      cta: "다이아몬드 둘러보기", next: "다음: 4C 가이드 →",
    },
    fourc: {
      title: "4C 가이드",
      caratH: "Carat — 캐럿", caratP: "스톤의 무게(1ct = 0.2g). 같은 캐럿이라도 컷에 따라 보이는 크기가 다릅니다.",
      cutH: "Cut — 컷", cutP: "광채를 결정하는 가장 중요한 요소. Excellent 컷은 빛을 최대로 반사합니다.",
      colorH: "Color — 컬러", colorP: "D(완전 무색)부터 Z까지. D–F는 무색, G–H는 거의 무색으로 육안 차이가 미미합니다.",
      clarityH: "Clarity — 클래리티", clarityP: "내포물의 정도. IF(무결점)–VS2까지는 육안으로 내포물이 보이지 않습니다.",
      tip: "팁: 예산 대비 가장 효율적인 조합은 Excellent 컷 + F–G 컬러 + VS1–VS2 클래리티입니다.",
      cta: "이 기준으로 주문제작 시작",
    },
  },
};

const zh = {
  nav: { diamonds: "钻石", designs: "设计", gallery: "设计画廊", process: "流程", custom: "定制订单", startCustom: "开始定制", guide: "指南", login: "登录", logout: "退出", account: "我的页面", vendorPortal: "供应商门户", admin: "管理后台" },
  common: {
    next: "下一步", prev: "上一步", submit: "提交", cancel: "取消", add: "添加", all: "全部",
    view: "查看详情", delete: "删除", new: "新建", none: "—", notFound: "找不到页面。", date: "日期", status: "状态",
  },
  shapes: { round: "圆形", oval: "椭圆形", princess: "公主方", emerald: "祖母绿形", pear: "梨形", marquise: "马眼形", cushion: "垫形", radiant: "雷迪恩形", asscher: "阿斯切形", heart: "心形" },
  metals: { wg18: "18K 白金", yg18: "18K 黄金", rg18: "18K 玫瑰金", pt950: "铂金 PT950" },
  categories: { ring: "戒指", necklace: "项链", earring: "耳环", bracelet: "手链" },
  status: {
    DRAFT: "草稿", SUBMITTED: "已提交", VENDOR_ASSIGNED: "已分配工坊",
    PROPOSAL_UPLOADED: "方案已上传", REVISION_REQUESTED: "已请求修改", CONFIRMED: "已确认",
    DEPOSIT_PAID: "已付定金", IN_PRODUCTION: "制作中", QUALITY_CHECK: "质检中",
    FINAL_PAYMENT_PAID: "已付尾款", SHIPPED: "配送中", DELIVERED: "已送达",
    COMPLETED: "已完成", CANCELLED: "已取消", ON_HOLD: "已搁置",
  },
  stages: { production: "制作中", qc: "质检", ready: "备货中", shipping: "配送中", delivered: "已送达" },
  login: {
    title: "登录", signupTitle: "注册", name: "姓名", email: "邮箱", password: "密码",
    loginBtn: "登录", signupBtn: "注册",
    toSignup: "新用户？注册账户", toLogin: "已有账户？登录",
    demoTitle: "演示账户（密码 demo1234）",
    staffTitle: "员工登录", staffSub: "BeloveD 运营管理后台。",
    vendorTitle: "工坊登录", vendorSub: "输入我们发送的访问码 — 无需密码。",
    codeLabel: "访问码", codeBtn: "进入",
    staffLink: "员工登录", vendorLink: "工坊登录", customerLink: "顾客登录",
    dealerApplyHint: "想成为经销商？", dealerApplyLink: "在此申请",
    errors: { badCredentials: "邮箱或密码不正确。（演示密码：demo1234）", emailExists: "该邮箱已注册。", wrongPortal: "该账户使用其他登录入口。", badCode: "访问码无效或已停用。", accountSuspended: "该账户已被停用。" },
  },
  diamonds: {
    title: "钻石", sub: "颗颗均为 IGI·GIA 认证培育钻石，经我们亲手检视，方与你相见。",
    caratMin: "克拉 min", caratMax: "克拉 max", maxPrice: "最高价格($)",
    cut: "切工", color: "颜色", clarity: "净度", cert: "证书", sort: "排序",
    sortPriceAsc: "价格从低到高", sortPriceDesc: "价格从高到低", sortCaratDesc: "克拉从高到低",
    byShape: "按形状选购", reset: "重置筛选", count: (n) => `${n} 颗钻石`, empty: "没有符合条件的钻石。",
  },
  detail: {
    notFound: "找不到该钻石。", shape: "形状", carat: "克拉", cut: "切工", color: "颜色",
    clarity: "净度", certOrg: "认证机构", certNo: "证书编号",
    certNote: (org, no) => `证书原件随实物一同提供。（${org} ${no}）`,
    orderCta: "用这颗钻石定制", back: "返回列表",
  },
  templates: {
    title: "设计画廊", sub: "BeloveD 工坊的签名设计。择一心仪，我们为你独家成就。",
    fromPrice: (p) => `镶嵌 ${p} 起`, quote: "询价",
  },
  wizard: {
    title: "定制订单", sub: "选定设计与钻石，工坊先以照片与影像呈上方案。确认之前，分文不取。",
    steps: ["① 设计", "② 钻石", "③ 详情", "④ 确认提交"],
    skipHint: "还没选好钻石？可以跳过 — 我们会按预算随方案推荐钻石。",
    nextNoStone: "暂不选钻石，下一步",
    metal: "金属", size: "尺寸（圈口/长度）", sizePh: "例：11号 / 42cm", engraving: "刻字（可选）",
    budget: "预算（$，可选）", notes: "需求说明",
    notesPh: "请描述想要的细节。（联系方式与外部链接将被自动屏蔽）",
    summary: "订单摘要", design: "设计", diamond: "钻石", recommend: "已请求工坊推荐",
    metalSize: "金属/尺寸", expected: "预估起价", quoteLater: "随方案提供报价",
    submitNote: "提交后工坊上传方案即可在此查看。确认方案并支付定金（30%）后开始制作。",
    submit: "提交订单", loginToSubmit: "登录后提交",
  },
  account: {
    title: "我的页面", welcome: (name) => `${name}，欢迎回来。`,
    tabs: { orders: "定制进度", payments: "付款记录", profile: "个人资料" },
    emptyOrders: "还没有订单。从这里开始：", gallery: "设计画廊",
    orderNo: "订单号", design: "设计", emptyPayments: "暂无付款记录。",
    when: "时间", type: "类型", amount: "金额", state: "状态", paid: "已支付",
    deposit: "定金", final: "尾款",
    nameLbl: "姓名", emailLbl: "邮箱", roleLbl: "角色", customerRole: "顾客",
    profileHint: "收货地址与联系方式在付款时填写（绝不会共享给工坊）。",
  },
  request: {
    notFound: "找不到该订单。",
    depositTitle: "定金支付", totalAmount: "制作总金额",
    depositLbl: (pct) => `定金（${pct}%）`, payDeposit: (amt) => `支付 ${amt}（模拟支付）`,
    mockNote: "正式服务中将跳转 Stripe 支付页面。",
    finalTitle: "尾款支付", qcHint: "质检进行中。支付尾款后开始配送。",
    payFinal: (amt) => `支付尾款 ${amt}（模拟支付）`,
    stagesTitle: "制作·配送阶段", tracking: "运单号", confirmReceipt: "确认收货",
    productionTitle: "制作过程", proposalsTitle: "方案",
    preparing: "工坊正在准备方案。方案上传后可在此查看并确认。",
    proposalV: (v) => `方案 v${v}`,
    confirmChip: "确认此方案", reviseChip: "请求修改",
    choices: { size: "调整尺寸", stone: "移动主石", band: "戒臂粗细", color: "色调", engraving: "刻字位置" },
    detailReq: "详细要求（联系方式·链接自动屏蔽）",
    confirmBtn: "确认方案", reviseBtn: "发送修改请求",
    confirmedNote: "✓ 已确认", revisionNote: (c) => `修改请求：${c}`,
    cancelOrder: "取消订单", cancelAsk: "确定取消该订单？",
  },
  vendor: {
    title: "供应商门户", sub: (name) => `${name} — 仅显示分配给您的订单。顾客信息匿名处理。`,
    tabs: { new: "待响应", waiting: "顾客审阅中", production: "制作·质检", done: "已完成" },
    empty: "该状态下没有订单。", order: "订单", design: "设计", elapsed: "已用时",
    hours: (h) => `${h}小时`, slaWarn: " 超出 SLA", work: "处理",
    notAssigned: "该订单未分配给您。",
    specTitle: "订单规格", diamondRow: "钻石", recommend: "已请求推荐钻石",
    metalRow: "金属", sizeRow: "尺寸", engravingRow: "刻字", budgetRow: "预算", notesRow: "需求说明",
    uploadTitle: (v) => `上传方案（v${v}）`, comment: "备注（联系方式·链接自动屏蔽）",
    uploadBtn: "上传方案",
    startTitle: "开始制作", startHint: "定金已支付。开始制作后顾客可看到进度。",
    startBtn: "开始制作",
    progressTitle: "制作进度", progressUpload: "上传进度照片", qcRequest: "制作完成 → 申请质检",
    prodLog: "制作过程记录", myProposals: "已上传的方案", noProposals: "还没有方案。请上传第一版方案。",
    fb: "顾客反馈", fbConfirmed: "✓ 已确认", fbRevise: (c) => `修改请求：${c}`,
  },
  picker: {
    hint: (n) => `已选 ${n} 个`,
    dropHint: "把照片或视频拖到这里", dropSub: "或点击从手机选择",
    sampleToggle: "或从样例中选择",
    limitHint: (n, max) => `已上传 ${n}/${max} 个 · 点击从手机选择`,
    maxError: (max) => `最多可上传 ${max} 张照片或视频。`,
    attachedLabel: "已上传文件", photoLabel: "照片", videoLabel: "视频", removeLabel: "删除",
    fileLabel: "上传文件", fileError: (mb) => `文件太大 — 请控制在 ${mb}MB 以内。`, typeError: "仅支持照片和视频。",
    optimizing: "正在优化媒体...",
    optimizedLabel: "已优化",
    optimizedNotice: (n) => `已压缩 ${n} 张图片用于上传。`,
    videoNotice: "视频已作为轻量预览文件添加，避免页面变慢。",
    optimizeError: "无法优化该文件。请尝试其他照片或视频。",
    labels: { sol: "单钻戒", band: "戒圈", pendant: "吊坠", studs: "耳钉", bracelet: "手链", loose: "裸石", video: "钻石视频" },
  },
  admin: {
    title: "管理后台",
    menu: { dashboard: "仪表盘", diamonds: "钻石", pool: "钻石池", templates: "模板", orders: "订单监管", vendors: "供应商", settings: "设置" },
    dash: {
      active: "进行中订单", unassigned: "未分配", sla: "SLA 超 48h", inventory: "库存钻石",
      slaWarn: (codes) => `供应商超 48 小时未响应：${codes} — 请在订单监管中重新分配。`,
      depositWait: (codes) => `等待定金：${codes}`, noOrders: "尚无已付款订单。",
    },
    pool: {
      title: "供应商钻石池", sub: "所有供应商的常备库存。可添加钻石、管理照片、归档任意条目。",
      filterAll: "全部供应商", supplier: "供应商", stone: "钻石", fourC: "4C", cert: "证书",
      cost: "成本", statusCol: "状态", photos: "照片", edit: "照片", save: "保存",
      archive: "归档", restore: "恢复", archived: "已归档",
      avail: { available: "有货", unavailable: "下架", sold: "已售" },
      newTitle: "添加钻石", addBtn: "加入池", count: (n) => `${n} 颗`,
    },
    dia: {
      bulkTitle: "批量价格调整", bulkBtn: (p) => `全部调整 ${p}%`,
      bulkHint: "正数 = 上调，负数 = 下调。按 $10 取整。",
      invTitle: "库存", stone: "钻石", fourC: "4C", cert: "证书",
      priceCol: "价格（$，直接修改）", visibleCol: "公开", pub: "公开", priv: "隐藏",
      newTitle: "登记新钻石（手动上传媒体）", shape: "形状", carat: "克拉", cut: "切工",
      color: "颜色", clarity: "净度", certOrg: "认证机构", certNo: "证书编号", price: "价格（$）", addBtn: "登记",
    },
    tpl: {
      title: "模板", name: "名称", category: "类别", basePrice: "镶嵌价", visibleCol: "公开",
      pub: "公开", priv: "隐藏", newTitle: "登记新模板（样品设计）", desc: "说明", addBtn: "登记",
      nameHint: "输入的文本将用于所有语言 — 之后可按语言本地化。",
    },
    orders: {
      title: "全部订单", order: "订单", customer: "顾客（PII — 仅管理员可见）", design: "设计",
      vendorCol: "供应商", payment: "付款", force: "强制转换", assign: "分配…", transit: "转换…",
      trackingPh: "输入运单号", dep: "定金", fin: "尾款",
    },
    vendors: {
      title: "供应商账户", displayName: "显示名", emailCol: "邮箱", assigned: "已分配订单",
      uploads: "已上传方案", stateCol: "状态", active: "启用", suspended: "停用",
      codeCol: "访问码", copyLink: "复制链接",
      issueTitle: "发放供应商账户", issueHint: "系统自动生成访问码 — 将访问码或魔法链接发给工坊。无需密码。",
      nameLbl: "显示名（例：ATELIER-03）", emailLbl: "邮箱",
      issueBtn: "发放访问码", issuedTitle: (n) => `${n} — 请将此发送给工坊`,
    },
    settings: {
      payTitle: "支付设置", depositPct: "定金比例（%）", applyNote: "自新确认的订单起生效。",
      stagesTitle: "配送阶段标签", heroTitle: "首页视频插槽",
      heroNote: "当前：/assets/diamond-noir-white.mp4 — 获得实拍素材后以同名文件替换即可立即生效。",
      demoTitle: "演示数据", resetBtn: "重置为种子数据", resetAsk: "确定重置所有演示数据？",
    },
  },
  guide: {
    hub: {
      kicker: "钻石指南",
      title: "从容抉择。",
      sub: "关于培育钻石品质、选石之道与定制决策的简明指南。",
      cards: {
        lab: { kicker: "培育钻石", title: "同样火彩，更聪明的来源。", body: "了解培育钻石的差异，以及哪些披露信息需要关注。" },
        fourc: { kicker: "4C", title: "切工、颜色、净度、克拉。", body: "用实用方式判断哪些因素最影响肉眼美感。" },
        custom: { kicker: "定制", title: "从需求到最终质检。", body: "开始定制订单后，每一步会发生什么。" },
      },
    },
    lab: {
      title: "什么是培育钻石？",
      p1: "培育钻石在物理、化学和光学性质上与天然钻石 100% 相同，是真正的钻石。唯一的区别是诞生地 — 在实验室中成长，而非地下。",
      h1: "与天然同质", p2: "硬度（莫氏 10）、折射率、色散完全相同。即便是宝石鉴定师，没有专业设备也无法区分。",
      h2: "IGI·GIA 认证", p3: "BeloveD 的每颗钻石都附带 IGI 或 GIA 证书，可凭编号查询真伪。",
      h3: "诚实定价", p4: "没有开采与流通溢价，同等预算可以选择更大、更纯净的钻石 — 价格约为天然钻石的一半。",
      cta: "浏览钻石", next: "下一篇：4C 指南 →",
    },
    fourc: {
      title: "4C 指南",
      caratH: "Carat — 克拉", caratP: "钻石的重量（1ct = 0.2g）。同样的克拉，切工不同，看起来的大小也不同。",
      cutH: "Cut — 切工", cutP: "决定光彩的最重要因素。Excellent 切工能最大程度反射光线。",
      colorH: "Color — 颜色", colorP: "从 D（完全无色）到 Z。D–F 为无色，G–H 接近无色，肉眼几乎无差别。",
      clarityH: "Clarity — 净度", clarityP: "内含物的程度。IF（无瑕）至 VS2 的内含物肉眼不可见。",
      tip: "提示：性价比最高的组合是 Excellent 切工 + F–G 颜色 + VS1–VS2 净度。",
      cta: "按此标准开始定制",
    },
  },
};

const es = {
  nav: { diamonds: "Diamantes", designs: "Diseños", gallery: "Galería de diseños", process: "Proceso", custom: "Pedido a medida", startCustom: "Crear pedido", guide: "Guía", login: "Iniciar sesión", logout: "Salir", account: "Mi página", vendorPortal: "Portal del taller", admin: "Admin" },
  common: {
    next: "Siguiente", prev: "Atrás", submit: "Enviar", cancel: "Cancelar", add: "Añadir", all: "Todo",
    view: "Ver detalle", delete: "Eliminar", new: "Nuevo", none: "—", notFound: "Página no encontrada.", date: "Fecha", status: "Estado",
  },
  shapes: { round: "Redondo", oval: "Ovalado", princess: "Princesa", emerald: "Esmeralda", pear: "Pera", marquise: "Marquesa", cushion: "Cojín", radiant: "Radiante", asscher: "Asscher", heart: "Corazón" },
  metals: { wg18: "Oro blanco 18K", yg18: "Oro amarillo 18K", rg18: "Oro rosa 18K", pt950: "Platino PT950" },
  categories: { ring: "Anillos", necklace: "Collares", earring: "Aretes", bracelet: "Pulseras" },
  status: {
    DRAFT: "Borrador", SUBMITTED: "Enviado", VENDOR_ASSIGNED: "Taller asignado",
    PROPOSAL_UPLOADED: "Propuesta lista", REVISION_REQUESTED: "Revisión solicitada", CONFIRMED: "Confirmado",
    DEPOSIT_PAID: "Depósito pagado", IN_PRODUCTION: "En producción", QUALITY_CHECK: "Control de calidad",
    FINAL_PAYMENT_PAID: "Pago final realizado", SHIPPED: "Enviado", DELIVERED: "Entregado",
    COMPLETED: "Completado", CANCELLED: "Cancelado", ON_HOLD: "En espera",
  },
  stages: { production: "En producción", qc: "Control de calidad", ready: "Preparando envío", shipping: "En camino", delivered: "Entregado" },
  login: {
    title: "Iniciar sesión", signupTitle: "Crear cuenta", name: "Nombre", email: "Correo", password: "Contraseña",
    loginBtn: "Entrar", signupBtn: "Crear cuenta",
    toSignup: "¿Primera vez? Crea una cuenta", toLogin: "¿Ya tienes cuenta? Inicia sesión",
    demoTitle: "Cuentas demo (contraseña: demo1234)",
    staffTitle: "Acceso de personal", staffSub: "Back office administrativo de BeloveD.",
    vendorTitle: "Acceso del taller", vendorSub: "Introduce el código de acceso que te enviamos — sin contraseña.",
    codeLabel: "Código de acceso", codeBtn: "Entrar",
    staffLink: "Acceso de personal", vendorLink: "Acceso del taller", customerLink: "Acceso de cliente",
    dealerApplyHint: "¿Quieres ser distribuidor?", dealerApplyLink: "Solicita aquí",
    errors: { rateLimited: "Demasiados intentos — prueba en un minuto.", badCredentials: "Correo o contraseña incorrectos. (Contraseña demo: demo1234)", emailExists: "Este correo ya está registrado.", wrongPortal: "Esta cuenta usa otro acceso.", badCode: "Código de acceso inválido o inactivo.", accountSuspended: "Esta cuenta está suspendida." },
  },
  diamonds: {
    title: "Diamantes", sub: "Diamantes de laboratorio certificados IGI·GIA — cada uno pasa por nuestras manos antes de llegar a las tuyas.",
    caratMin: "Quilates mín", caratMax: "Quilates máx", maxPrice: "Precio máx ($)",
    cut: "Talla", color: "Color", clarity: "Pureza", cert: "Certificado", sort: "Ordenar",
    sortPriceAsc: "Precio: menor a mayor", sortPriceDesc: "Precio: mayor a menor", sortCaratDesc: "Quilates: mayor a menor",
    byShape: "Comprar por forma", reset: "Restablecer filtros", count: (n) => `${n} piedras`, empty: "Ningún diamante coincide con los filtros.",
  },
  detail: {
    notFound: "Diamante no encontrado.", shape: "Forma", carat: "Quilates", cut: "Talla", color: "Color",
    clarity: "Pureza", certOrg: "Certificado por", certNo: "N.º de certificado",
    certNote: (org, no) => `El certificado original se entrega con la pieza. (${org} ${no})`,
    orderCta: "Pedido a medida con este diamante", back: "Volver a la lista",
  },
  templates: {
    title: "Galería de diseños", sub: "Diseños firmados por el atelier BeloveD. Elige uno — lo haremos solo tuyo.",
    fromPrice: (p) => `Engaste desde ${p}`, quote: "Cotización a pedido",
  },
  wizard: {
    title: "Pedido a medida", sub: "Elige diseño y piedra — el atelier te presenta propuestas en fotos y video primero. No pagas nada hasta confirmar.",
    steps: ["① Diseño", "② Diamante", "③ Detalles", "④ Revisión"],
    skipHint: "¿Aún sin decidir? Omite este paso — propondremos piedras según tu presupuesto.",
    nextNoStone: "Continuar sin piedra",
    metal: "Metal", size: "Talla (anillo / longitud)", sizePh: "ej.: talla 11 / 42cm", engraving: "Grabado (opcional)",
    budget: "Presupuesto ($, opcional)", notes: "Solicitudes",
    notesPh: "Describe los detalles que deseas. (Los datos de contacto y enlaces se bloquean automáticamente)",
    summary: "Resumen del pedido", design: "Diseño", diamond: "Diamante", recommend: "Recomendación del taller solicitada",
    metalSize: "Metal / Talla", expected: "Estimado desde", quoteLater: "Cotización junto con la propuesta",
    submitNote: "Tras enviar, el taller sube propuestas aquí. La producción comienza solo después de confirmar y pagar el depósito (30%).",
    submit: "Enviar pedido", loginToSubmit: "Inicia sesión para enviar",
  },
  account: {
    title: "Mi página", welcome: (name) => `Bienvenido/a, ${name}.`,
    tabs: { orders: "Pedidos a medida", payments: "Pagos", profile: "Perfil" },
    emptyOrders: "Aún no hay pedidos. Empieza en la", gallery: "Galería de diseños",
    orderNo: "Pedido", design: "Diseño", emptyPayments: "Sin pagos todavía.",
    when: "Fecha", type: "Tipo", amount: "Importe", state: "Estado", paid: "Pagado",
    deposit: "Depósito", final: "Pago final",
    nameLbl: "Nombre", emailLbl: "Correo", roleLbl: "Rol", customerRole: "Cliente",
    profileHint: "La dirección y el contacto se piden al pagar (nunca se comparten con el taller).",
  },
  request: {
    notFound: "Pedido no encontrado.",
    depositTitle: "Pago del depósito", totalAmount: "Coste total de producción",
    depositLbl: (pct) => `Depósito (${pct}%)`, payDeposit: (amt) => `Pagar ${amt} (pago simulado)`,
    mockNote: "En producción se abre el checkout de Stripe.",
    finalTitle: "Pago final", qcHint: "Control de calidad en curso. El envío comienza tras el pago final.",
    payFinal: (amt) => `Pagar saldo ${amt} (pago simulado)`,
    stagesTitle: "Producción y envío", tracking: "N.º de seguimiento", confirmReceipt: "Confirmar recepción",
    productionTitle: "Registro de producción", proposalsTitle: "Propuestas",
    preparing: "El taller está preparando tu propuesta. Podrás revisarla y confirmarla aquí.",
    proposalV: (v) => `Propuesta v${v}`,
    confirmChip: "Confirmar esta propuesta", reviseChip: "Solicitar revisión",
    choices: { size: "Ajustar talla", stone: "Mover la piedra", band: "Grosor del aro", color: "Tono de color", engraving: "Posición del grabado" },
    detailReq: "Detalles (datos de contacto y enlaces bloqueados)",
    confirmBtn: "Confirmar propuesta", reviseBtn: "Enviar solicitud de revisión",
    confirmedNote: "✓ Confirmado", revisionNote: (c) => `Revisión solicitada: ${c}`,
    cancelOrder: "Cancelar pedido", cancelAsk: "¿Cancelar este pedido?",
  },
  vendor: {
    title: "Portal del taller", sub: (name) => `${name} — solo se muestran tus pedidos asignados. Los clientes permanecen anónimos.`,
    tabs: { new: "Pendiente de respuesta", waiting: "Cliente revisando", production: "Producción y QC", done: "Finalizados" },
    empty: "No hay pedidos en este estado.", order: "Pedido", design: "Diseño", elapsed: "Transcurrido",
    hours: (h) => `${h}h`, slaWarn: " SLA excedido", work: "Abrir",
    notAssigned: "Este pedido no está asignado a ti.",
    specTitle: "Especificación del pedido", diamondRow: "Diamante", recommend: "Recomendación de piedra solicitada",
    metalRow: "Metal", sizeRow: "Talla", engravingRow: "Grabado", budgetRow: "Presupuesto", notesRow: "Solicitudes",
    uploadTitle: (v) => `Subir propuesta (v${v})`, comment: "Comentario (datos de contacto y enlaces bloqueados)",
    uploadBtn: "Subir propuesta",
    startTitle: "Iniciar producción", startHint: "Depósito recibido. Al iniciar, el cliente verá el progreso.",
    startBtn: "Iniciar producción",
    progressTitle: "Progreso de producción", progressUpload: "Subir fotos de progreso", qcRequest: "Terminado → solicitar QC",
    prodLog: "Registro de producción", myProposals: "Propuestas subidas", noProposals: "Aún no hay propuestas. Sube la primera.",
    fb: "Comentarios del cliente", fbConfirmed: "✓ Confirmado", fbRevise: (c) => `Revisión: ${c}`,
  },
  picker: {
    hint: (n) => `${n} seleccionados`,
    dropHint: "Arrastra fotos o videos aquí", dropSub: "o toca para elegir desde tu teléfono",
    sampleToggle: "O elige una muestra",
    limitHint: (n, max) => `${n}/${max} adjuntos · toca para elegir desde tu teléfono`,
    maxError: (max) => `Puedes adjuntar hasta ${max} fotos o videos.`,
    attachedLabel: "Archivos adjuntos", photoLabel: "Foto", videoLabel: "Video", removeLabel: "Eliminar",
    fileLabel: "Subir archivo", fileError: (mb) => `Archivo muy grande — menos de ${mb}MB.`, typeError: "Solo se admiten fotos y videos.",
    optimizing: "Optimizando archivos...",
    optimizedLabel: "Optimizado",
    optimizedNotice: (n) => `${n} imagen${n > 1 ? "es" : ""} comprimida${n > 1 ? "s" : ""} para subir.`,
    videoNotice: "Video añadido como archivo de vista previa optimizado.",
    optimizeError: "No se pudo optimizar ese archivo. Prueba otra foto o video.",
    labels: { sol: "Solitario", band: "Aro", pendant: "Colgante", studs: "Aretes", bracelet: "Pulsera", loose: "Piedra suelta", video: "Video de piedra" },
  },
  admin: {
    title: "Admin",
    menu: { dashboard: "Panel", diamonds: "Diamantes", pool: "Pool de Diamantes", templates: "Plantillas", orders: "Pedidos", vendors: "Proveedores", settings: "Ajustes" },
    dash: {
      active: "Pedidos activos", unassigned: "Sin asignar", sla: "SLA +48h", inventory: "Piedras en inventario",
      slaWarn: (codes) => `Taller sin responder más de 48h: ${codes} — reasigna en Pedidos.`,
      depositWait: (codes) => `Esperando depósito: ${codes}`, noOrders: "Aún no hay pedidos pagados.",
    },
    pool: {
      title: "Pool de Diamantes", sub: "Stock permanente de todos los proveedores. Añade piedras, gestiona fotos y archiva.",
      filterAll: "Todos los proveedores", supplier: "Proveedor", stone: "Piedra", fourC: "4C", cert: "Certificado",
      cost: "Costo", statusCol: "Estado", photos: "Fotos", edit: "Fotos", save: "Guardar",
      archive: "Archivar", restore: "Restaurar", archived: "Archivado",
      avail: { available: "Disponible", unavailable: "Retirada", sold: "Vendida" },
      newTitle: "Añadir piedra", addBtn: "Añadir al pool", count: (n) => `${n} piedras`,
    },
    dia: {
      bulkTitle: "Ajuste de precios masivo", bulkBtn: (p) => `Ajustar todo ${p}%`,
      bulkHint: "Positivo = subir, negativo = bajar. Redondeado a $10.",
      invTitle: "Inventario", stone: "Piedra", fourC: "4C", cert: "Certificado",
      priceCol: "Precio ($, edición directa)", visibleCol: "Visible", pub: "Público", priv: "Oculto",
      newTitle: "Añadir diamante (subida manual de medios)", shape: "Forma", carat: "Quilates", cut: "Talla",
      color: "Color", clarity: "Pureza", certOrg: "Certificadora", certNo: "N.º certificado", price: "Precio ($)", addBtn: "Añadir",
    },
    tpl: {
      title: "Plantillas", name: "Nombre", category: "Categoría", basePrice: "Precio base", visibleCol: "Visible",
      pub: "Público", priv: "Oculto", newTitle: "Añadir plantilla (diseño de muestra)", desc: "Descripción", addBtn: "Añadir",
      nameHint: "El texto introducido se usa para todos los idiomas — se puede localizar después.",
    },
    orders: {
      title: "Todos los pedidos", order: "Pedido", customer: "Cliente (PII — solo admin)", design: "Diseño",
      vendorCol: "Taller", payment: "Pago", force: "Transición forzada", assign: "Asignar…", transit: "Transición…",
      trackingPh: "N.º de seguimiento", dep: "Depósito", fin: "Final",
    },
    vendors: {
      title: "Cuentas de proveedor", displayName: "Nombre visible", emailCol: "Correo", assigned: "Asignados",
      uploads: "Propuestas", stateCol: "Estado", active: "Activo", suspended: "Suspendido",
      codeCol: "Código de acceso", copyLink: "Copiar enlace",
      issueTitle: "Emitir cuenta de proveedor", issueHint: "Se genera un código de acceso automáticamente — comparte el código o el enlace mágico con el taller. Sin contraseña.",
      nameLbl: "Nombre visible (ej.: ATELIER-03)", emailLbl: "Correo",
      issueBtn: "Emitir código de acceso", issuedTitle: (n) => `${n} — envía esto al taller`,
    },
    settings: {
      payTitle: "Ajustes de pago", depositPct: "Porcentaje de depósito (%)", applyNote: "Se aplica a los pedidos confirmados a partir de ahora.",
      stagesTitle: "Etiquetas de etapas de envío", heroTitle: "Slot del video principal",
      heroNote: "Actual: /assets/diamond-noir-white.mp4 — reemplaza el archivo para usar metraje real al instante.",
      demoTitle: "Datos de demostración", resetBtn: "Restablecer datos de ejemplo", resetAsk: "¿Restablecer todos los datos de demo?",
    },
  },
  guide: {
    hub: {
      kicker: "Guía de diamantes",
      title: "Elige con serenidad.",
      sub: "Notas breves y prácticas sobre calidad, elección de piedra y las decisiones de una pieza a medida.",
      cards: {
        lab: { kicker: "Laboratorio", title: "Mismo fuego. Origen más inteligente.", body: "Cómo se comparan los diamantes de laboratorio y qué detalles importan." },
        fourc: { kicker: "4C", title: "Talla, color, pureza, quilates.", body: "Una forma práctica de priorizar el brillo visible." },
        custom: { kicker: "A medida", title: "Del brief al QC final.", body: "Qué ocurre después de iniciar un pedido a medida." },
      },
    },
    lab: {
      title: "¿Qué es un diamante de laboratorio?",
      p1: "Un diamante de laboratorio es un diamante real — física, química y ópticamente idéntico al extraído de una mina. La única diferencia es su lugar de nacimiento: un laboratorio en vez del subsuelo.",
      h1: "Idéntico al natural", p2: "Misma dureza (Mohs 10), índice de refracción y dispersión. Ni un gemólogo puede distinguirlos sin equipo especializado.",
      h2: "Certificado IGI · GIA", p3: "Cada piedra de BeloveD incluye un certificado IGI o GIA verificable por su número.",
      h3: "Precio honesto", p4: "Sin primas de minería ni distribución: una piedra más grande y limpia por el mismo presupuesto — a la mitad de precio.",
      cta: "Ver diamantes", next: "Siguiente: Guía de las 4C →",
    },
    fourc: {
      title: "Guía de las 4C",
      caratH: "Carat — Quilates", caratP: "El peso de la piedra (1ct = 0,2g). El mismo quilataje puede verse más grande o pequeño según la talla.",
      cutH: "Cut — Talla", cutP: "El factor más importante para el brillo. Una talla Excellent devuelve el máximo de luz.",
      colorH: "Color", colorP: "De D (incoloro) a Z. D–F son incoloros; G–H casi incoloros, con diferencias invisibles a simple vista.",
      clarityH: "Clarity — Pureza", clarityP: "El grado de inclusiones. De IF (impecable) hasta VS2, las inclusiones son invisibles a simple vista.",
      tip: "Consejo: la combinación más eficiente es talla Excellent + color F–G + pureza VS1–VS2.",
      cta: "Empezar un pedido con estos criterios",
    },
  },
};

export const platformStrings = { en, ko, zh, es };
